### ISSUE TITLE
Surviving host reboots

### ISSUE THREAD

**Issue by wilkko** [vfarcic/docker-flow-proxy#12]
How to keep proxy configuration in place after host reboots without having to reconfigure the proxy?

**Comment by vfarcic** [comment]
All the configuration files are stored inside container directory `/cfg/`. If you expose it as a volume, data would be persisted after host reboots.

I'm currently working on an improvement that will not require a volume. Every time a reconfigure request is sent, the proxy will store all the information in Consul. When the proxy container is started, it will first request data from Consul and if there is any, reconfigure itself for all the services. That will mean not only that it will survive reboots without exposing a volume but it will also survive if the whole node is destroyed. As long as at least one Consul is running, the data is safe and the proxy will be able to reconfigure itself when the container is started.

Would that fit your needs?

**Comment by wilkko** [comment]
Sounds good. I'll put volumes in place until that. CoreOS autoupdates and therefore reboots have been a good "chaos monkey" for us =)

**Comment by wilkko** [comment]
I cannot get the volume approach to work. The configuration files are not available at all when a volume is added to `/cfg/`

Here's my Ansible playbook to install proxy:

`- name: 'launch proxy data container'
  docker:
    image: 'busybox'
    name: 'proxy-data'
    state: 'present'
    volumes:
      - '/cfg'

- name: 'launch Docker flow proxy container'
  docker:
    image: "vfarcic/docker-flow-proxy:{{ proxy_version }}"
    name: 'proxy'
    state: "{{ container_state }}"
    hostname: "{{ container_hostname }}"
    restart_policy: "{{ container_restart_policy }}"
    net: 'default' # https://github.com/ansible/ansible-modules-core/issues/1885
    env:
      CONSUL_ADDRESS: "{{ consul_location }}"
    links:
      - 'consul:consul'
    volumes_from:
      - 'proxy-data'
    ports:
      - "{{ proxy_host_port }}:80"
      - "{{ proxy_api_host_port }}:8080"`

**Comment by wilkko** [comment]
Also tried

```
- name: launch Docker flow proxy container
  docker:
    image: "vfarcic/docker-flow-proxy:{{ proxy_version }}"
    name: 'proxy'
    state: "{{ container_state }}"
    hostname: "{{ container_hostname }}"
    restart_policy: "{{ container_restart_policy }}"
    net: default # https://github.com/ansible/ansible-modules-core/issues/1885
    env:
      CONSUL_ADDRESS: "{{ consul_location }}"
    links:
      - 'consul:consul'
    volumes:
      - /opt/docker-flow-proxy/cfg:/cfg
    ports:
      - "{{ proxy_host_port }}:80"
      - "{{ proxy_api_host_port }}:8080"
```
