### ISSUE TITLE
Forward https traffic to backend

### ISSUE THREAD

**Issue by n1b0r** [vfarcic/docker-flow-proxy#139]
Hello,

I'm trying to setup docker-flow-proxy to proxy requests to a gitlab docker instance (from image gitlab/gitlab-ce).

I'm not familiar with cert and https stuff.

The gitlab instance is configured to listen on https, so I would like something like

```
--HTTPS--> DFP --HTTPS--> gitlab
```

Given the following setup, it's not working and the gitlab instance respond :

```
400 Bad Request
The plain HTTP request was sent to HTTPS port
nginx
```

Which seems that the request as been send as http ?

Here is the gitlab service stack file :

```
version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ce:rc
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
      - le-certs:/etc/gitlab/ssl
    networks:
     - proxy
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=git.nibor.me,docker.nibor.me
        - com.df.servicePath=/
        - com.df.srcPort=443
        - com.df.port=443
```

And the proxy stack file :

```
version: "3"
services:

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - SERVICE_NAME=proxy_proxy
    deploy:
      replicas: 1

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy-le:8080/v1/docker-flow-proxy-letsencrypt/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy_proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]
```

Certificates are correctly inserted into DFP via put requests.

Here is generated configuration :

```
/ # curl http://proxy_proxy:8080/v1/docker-flow-proxy/config
global
    pidfile /var/run/haproxy.pid
    tune.ssl.default-dh-param 2048

    #disable sslv3, prefer modern ciphers
    ssl-default-bind-options no-sslv3
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

    ssl-default-server-options no-sslv3
    ssl-default-server-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

defaults
    mode    http
    balance roundrobin

    option  dontlognull
    option  dontlog-normal
    option  http-server-close
    option  forwardfor
    option  redispatch

    errorfile 400 /errorfiles/400.http
    errorfile 403 /errorfiles/403.http
    errorfile 405 /errorfiles/405.http
    errorfile 408 /errorfiles/408.http
    errorfile 429 /errorfiles/429.http
    errorfile 500 /errorfiles/500.http
    errorfile 502 /errorfiles/502.http
    errorfile 503 /errorfiles/503.http
    errorfile 504 /errorfiles/504.http

    maxconn 5000
    timeout connect 5s
    timeout client  20s
    timeout server  20s
    timeout queue   30s
    timeout tunnel  3600s
    timeout http-request 5s
    timeout http-keep-alive 15s

    stats enable
    stats refresh 30s
    stats realm Strictly\ Private
    stats auth admin:admin
    stats uri /admin?stats

frontend services
    bind *:80
    bind *:443 ssl crt /certs/git.nibor.me.pem crt /certs/docker.nibor.me.pem
    mode http

    acl url_gitlab_gitlab443 path_beg /
    acl srcPort_gitlab_gitlab443 dst_port 443
    acl domain_gitlab_gitlab hdr(host) -i git.nibor.me docker.nibor.me
    redirect scheme https if !{ ssl_fc } url_gitlab_gitlab443 domain_gitlab_gitlab srcPort_gitlab_gitlab443
    use_backend gitlab_gitlab-be443 if url_gitlab_gitlab443 domain_gitlab_gitlab srcPort_gitlab_gitlab443
    acl url_proxy_proxy-le8080 path_beg /.well-known/acme-challenge
    use_backend proxy_proxy-le-be8080 if url_proxy_proxy-le8080






backend gitlab_gitlab-be443
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server gitlab_gitlab gitlab_gitlab:443


backend proxy_proxy-le-be8080
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server proxy_proxy-le proxy_proxy-le:8080/
```

Few links on internet could be helpfull :
  * https://raymii.org/s/snippets/haproxy_ssl_backends.html
  * https://gitlab.com/gitlab-cookbooks/gitlab-haproxy/blob/master/templates/default/haproxy.cfg.erb

They are using **ssl verify none**.

What other logs could be relevant ?
Did you already encountered this kind of problem ?

Robin.

**Comment by vfarcic** [comment]
I don't think you should setup SSL for GitLab. If SSL is setup on the proxy side that should be enough (and preferable). Is there a specific reason you want to have certs both in the proxy and GitLab?

**Comment by n1b0r** [comment]
Gitlab docker image include several services inside the container like the docker registry integrated into gitlab.
As far as I know, for docker registry I will need a complete https traffic isn't it ?

**Comment by vfarcic** [comment]
If certs are inside the proxy, from the point of view of consumers, all communication is HTTPS.

I'll try the GitLab image tomorrow and, hopefully, be able to come up with a config that works.

**Comment by n1b0r** [comment]
ok thank you, please tell me if you need configuration examples.
In my setup I activated **external_url** to https://git.nibor.me and **registry_external_url** to https://docker.nibor.me

**Comment by n1b0r** [comment]
> If certs are inside the proxy, from the point of view of consumers, all communication is HTTPS.

That's fine if backend service is not able to receive https.

I used a lot jwilder nginx-proxy with jcrs letsencrypt-companion without swarm mode. I often stopped https traffic at proxy with services not correctly handling https.

Gitlab is a little bit special (IMHO) as :
  * if we use https in external_url, gitlab will automatically load certificates, so I presume it needs https traffic. For the moment, the best I get is the 400 response, wich also seems to indicate that https traffic is required.
  * with docker registry enabled, we also need https traffic until the backend.

**Comment by vfarcic** [comment]
I don't have a certificate at hand to test changes and would appreciate if you could give me a hand with this issue. If you can, the steps are as follows.

1. Run the proxy with the port `8080` opened. Make sure that only one replica is running.
2. Enter inside the service container and edit the `/cfg/haproxy.cfg` file.
3. Reload the proxy by sending a [Reload](https://proxy.dockerflow.com/usage/#reload) request.
4. Check whether the changes to the config provide the functionality you need. If it doesn't, repeat steps 2 to 4.

If you could do that (figure out what is missing in the HAProxy config), I can easily add it to the project.

Please let me know if you're OK with that.

**Comment by n1b0r** [comment]
Hey,

Using your steps I edited the config to :

```
/ # curl http://proxy_proxy:8080/v1/docker-flow-proxy/config
global
    pidfile /var/run/haproxy.pid
    tune.ssl.default-dh-param 2048

    #disable sslv3, prefer modern ciphers
    ssl-default-bind-options no-sslv3
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

    ssl-default-server-options no-sslv3
    ssl-default-server-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

defaults
    mode    http
    balance roundrobin

    option  dontlognull
    option  dontlog-normal
    option  http-server-close
    option  forwardfor
    option  redispatch

    errorfile 400 /errorfiles/400.http
    errorfile 403 /errorfiles/403.http
    errorfile 405 /errorfiles/405.http
    errorfile 408 /errorfiles/408.http
    errorfile 429 /errorfiles/429.http
    errorfile 500 /errorfiles/500.http
    errorfile 502 /errorfiles/502.http
    errorfile 503 /errorfiles/503.http
    errorfile 504 /errorfiles/504.http

    maxconn 5000
    timeout connect 5s
    timeout client  20s
    timeout server  20s
    timeout queue   30s
    timeout tunnel  3600s
    timeout http-request 5s
    timeout http-keep-alive 15s

    stats enable
    stats refresh 30s
    stats realm Strictly\ Private
    stats auth admin:admin
    stats uri /admin?stats

frontend services
    bind *:80
    bind *:443 ssl crt /certs/git.nibor.me.pem crt /certs/docker.nibor.me.pem
    mode http

    acl url_gitlab_gitlab443 path_beg /
    acl srcPort_gitlab_gitlab443 dst_port 443
    acl domain_gitlab_gitlab hdr(host) -i git.nibor.me docker.nibor.me
    redirect scheme https if !{ ssl_fc } url_gitlab_gitlab443 domain_gitlab_gitlab srcPort_gitlab_gitlab443
    use_backend gitlab_gitlab-be443 if url_gitlab_gitlab443 domain_gitlab_gitlab srcPort_gitlab_gitlab443
    acl url_proxy_proxy-le8080 path_beg /.well-known/acme-challenge
    use_backend proxy_proxy-le-be8080 if url_proxy_proxy-le8080






backend gitlab_gitlab-be443
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server gitlab_gitlab gitlab_gitlab:443 ssl verify none


backend proxy_proxy-le-be8080
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server proxy_proxy-le proxy_proxy-le:8080/
```

Now the gitlab instance is correctly handling my request.

I would like to purpose a merge request but what kind of parameter can we use to detect that we need the **ssl verify none** ?

**Comment by vfarcic** [comment]
I just added a [Reconfigure](https://proxy.dockerflow.com/usage/#reconfigure) parameter `sslVerifyNone`. If set to `true`, backend will receive `ssl verify none`. Can you please try it out and let me know whether it works from your end?

**Comment by n1b0r** [comment]
thats awesome, my gitlab services are working, including the internal registry !

**Comment by hamburml** [comment]
@n1b0r Could you please show your stack file? In the future I also want to have gitlab with internal registry running inside swarm. Thx :)

**Comment by n1b0r** [comment]
hey, here is my current gitlab stack file.

```
version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-logs:/var/log/gitlab
      - gitlab-data:/var/opt/gitlab
      - le-certs:/etc/gitlab/ssl
    networks:
      - proxy
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=git.domain.tld,docker.domain.tld
        - com.df.servicePath=/
        - com.df.srcPort=443
        - com.df.port=443
        - com.df.letsencrypt.host=git.domain.tld,docker.domain.tld
        - com.df.letsencrypt.email=email@gmail.com
        - com.df.sslVerifyNone=true

  runner:
    image: gitlab/gitlab-runner:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - gitlab-runner:/etc/gitlab-runner

volumes:
  gitlab-config:
    external: true
  gitlab-logs:
    external: true
  gitlab-data:
    external: true
  gitlab-runner:
    external: true
  le-certs:
    external: true
networks:
  proxy:
    external: true
```

with this setup, setting external_url and registry_external_url in gitlab.rb conf did the job.
