### ISSUE TITLE
Docker swarm error messages

### ISSUE THREAD

**Issue by wilkko** [vfarcic/docker-flow-proxy#15]
Took me while to figure out the the error was coming from Swarm not being able to parse something in the docker compose file. Maybe the error messages could be improved a bit?

```
docker-flow -f books/docker-compose-test.yml -b -p books -t books -c http://consul-1.example.com:8500 -F deploy
>> Docker Flow: Deploying (books-blue)...
Pulling books-blue (docker.example.com/books:master)...
No stopped containers
Creating books_books-blue_1
json: cannot unmarshal string into Go value of type int64
>> Docker Flow: The deployment phase failed (up)
Docker Compose command &{/usr/local/bin/docker-compose [docker-compose -f docker-compose-flow.yml.tmp -p books up -d books-blue] []  <nil> 0xc208036008 0xc208036010 [] <nil> 0xc20801f1a0 exit status 1 <nil> true [0xc2080360d0 0xc208036008 0xc208036010] [0xc2080360d0] [] [] 0xc20802a720}
exit status 1
```

In fact the cpu_shares was in wrong format:

```
books:
    image: docker.example.com/books:${IMAGE_TAG}
    restart: always
    ports:
      - '8080'
    environment:
      - SERVICE_8080_NAME=${SERVICE_NAME}
      - SERVICE_TAGS=${SERVICE_TAGS}
      - SERVICE_8080_CHECK_HTTP=${HEALTH_CHECK_PATH}
    cpu_shares: 0,1
    mem_limit: 300M
```
