### ISSUE TITLE
Place `servicePath=/` at the bottom of the config

### ISSUE THREAD

**Issue by vfarcic** [vfarcic/docker-flow-proxy#151]
No matter the ordering through `serviceName` and `aclName`, when `servicePath` is `/`, it should be placed at the bottom of the config. That way, catch all problem will be avoided and users will not need to use `aclName` to place the ACL at the bottom of the config.

More info can be found in the conversation in the issue #149.

**Comment by vfarcic** [comment]
Added to the [release 1.230](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.230).

**Comment by mhabegger** [comment]
@vfarcic which means the aclName we were discussing yesterday with @hamburml on the let's encrypt flow is not necessary any more ?

**Comment by vfarcic** [comment]
@mhabegger The `aclName` param is not anymore necessary for services with `servicePath=/`. The param still has its purpose for ordering ACLs, but not as a way to put root service to the bottom.

While we are at this subject, can you please try it out and let me know how it went. The feature passed all my automated tests but I still didn't have time to try it out manually. I'm confident that it'll work but an additional verification would not do any harm.

**Comment by stowns** [comment]
Doesn't appear to be working correctly for me. I may be missing something but here's the behavior I'm viewing

```
myService:
    image: "myService:latest"
    networks:
      - default
      - proxy
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/myService
        - com.df.reqPathSearch=/myService/
        - com.df.reqPathReplace=/
        - com.df.port=3000

ui:
    image: "ui:latest"
    networks:
      - default
      - proxy
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=80
```

Calls to /myService/myPath (a REST api) are serving up NGINX 502 errors from ui. I would expect

GET /myService/myPath -> myService: /myPath
GET /aView -> ui: /aView

**Comment by vfarcic** [comment]
@stowns It would help a lot if you could include the config of the proxy.

If the proxy has the port `8080` opened, you can get it with the [config request](http://proxy.dockerflow.com/usage/#config). Otherwise, you can get it with the command that follows.

```bash
docker container exec -it [ID] cat /cfg/haproxy.cfg
```

Please replace `[ID]` with the ID of one of the proxy containers.

**Comment by stowns** [comment]
```
global pidfile /var/run/haproxy.pid tune.ssl.default-dh-param 2048 log 127.0.0.1:1514 local0 #disable sslv3, prefer modern ciphers ssl-default-bind-options no-sslv3 ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS ssl-default-server-options no-sslv3 ssl-default-server-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS defaults mode http balance roundrobin option http-server-close option forwardfor option redispatch errorfile 400 /errorfiles/400.http errorfile 403 /errorfiles/403.http errorfile 405 /errorfiles/405.http errorfile 408 /errorfiles/408.http errorfile 429 /errorfiles/429.http errorfile 500 /errorfiles/500.http errorfile 502 /errorfiles/502.http errorfile 503 /errorfiles/503.http errorfile 504 /errorfiles/504.http maxconn 5000 timeout connect 5s timeout client 20s timeout server 20s timeout queue 30s timeout tunnel 3600s timeout http-request 5s timeout http-keep-alive 15s stats enable stats refresh 30s stats realm Strictly\ Private stats auth admin:admin stats uri /admin?stats frontend services bind *:80 bind *:443 ssl crt /run/secrets/myserver.pem mode http option httplog log

global 
  acl url_awesome-stack_myService3000 path_beg /myService 
  use_backend awesome-stack_myService-be3000 if url_awesome-stack_myService3000 

  acl url_awesome-stack_ui80 path_beg / 
  use_backend awesome-stack_ui-be80 if url_awesome-stack_ui80

backend awesome-stack_ui-be80 mode http log global server awesome-stack_ui awesome-stack_ui:80

backend awesome-stack_myService-be3000 mode http log global http-request set-path %[path,regsub(/myService/,/)] server awesome-stack_myService awesome-stack_myService:3000
```

**Comment by vfarcic** [comment]
That's very strange...

ACLs are ordered correctly. The one with the path `/` is at the end (as it should be).

Assuming that the services you're using are private, I cannot easily reproduce the situation.

I see that you're running it in `DEBUG` mode. Can you post the logs as well?

**Comment by stowns** [comment]
Fail on my end. The uri was stale. Browser was autocompleting an old one. Explains why the logs weren't adding up and the wrong service was being hit. Sorry for the confusion.

**Comment by vfarcic** [comment]
I'm glad it worked out @stowns 

Closing the ticket...

**Comment by srigi** [comment]
Hi @vfarcic 

I still have problem that root `/` path is not at the end of `haproxy.cfg`. I was able to distil minimal example:

**docker-compose.yml**
```yaml
version: '3'

services:
  aaa:
    image: nginx:alpine
    networks:
      - proxy
    deploy:
      labels:
        - com.df.notify=true
        - com.df.serviceDomain=test.reviewapps.example.com
        - com.df.servicePath=/
        - com.df.port=80

  bbb:
    image: nginx:alpine
    networks:
      - proxy
    deploy:
      labels:
        - com.df.notify=true
        - com.df.serviceDomain=test.reviewapps.example.com
        - com.df.servicePath=/api
        - com.df.port=80

networks:
  proxy:
    external: true
```

Resulting in **haproxy.cfg**

```
...

frontend services
    bind *:80
    bind *:443
    mode http

    acl url_test_aaa80_0 path_beg /
    acl domain_test_aaa80_0 hdr(host) -i test.reviewapps.example.com
    use_backend test_aaa-be80_0 if url_test_aaa80_0 domain_test_aaa80_0
    acl url_test_bbb80_0 path_beg /api
    acl domain_test_bbb80_0 hdr(host) -i test.reviewapps.example.com
    use_backend test_bbb-be80_0 if url_test_bbb80_0 domain_test_bbb80_0

backend test_aaa-be80_0
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server test_aaa test_aaa:80

backend test_bbb-be80_0
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server test_bbb test_bbb:80
```

Rearranging services in **docker-compose.yml** doesn't affect result. **But if I rename** service `aaa` to `caa` (to be alphabetically after `bbb`), the `/api` route gets above of `/` in **haproxy.cfg**.
