### ISSUE TITLE
http and tcp modes simultaneously in the same service

### ISSUE THREAD

**Issue by marceloaguero** [vfarcic/docker-flow-proxy#202]
Hi.

I want to implement a service (https://github.com/dcm4che/dcm4chee-arc-light/wiki/Running-on-Docker) that uses ports 8080, 9990 (http), 11112 and 2575 (tcp). I have no problem using Docker Flow Proxy in swarm mode only with the ports in http mode simply by specifying the following in my docker-compose.yml for the proxy stack:

```
version: "3"
services:
  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
      - 9990:9990
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - BIND_PORTS=9990
...
```

And, in the yml file for the service stack:

```
...
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath.1=/
        - com.df.port.1=8080
        - com.df.srcPort.1=80
        - com.df.servicePath.2=/
        - com.df.port.2=9990
        - com.df.srcPort.2=9990
...
```

But in addition to those http ports, I need the proxy listening the other ports in tcp mode as well (11112 and 2575).

As reqMode is "global", I can't differentiate the traffic. If there was something like com.df.reqMode.1, com.df.reqMode.2 I think it would be ideal.

Or is there any other way to achieve what I need?

**Comment by marceloaguero** [comment]
If I manually add the required frontends and backends configuration to haproxy, everything works well. For example, for 11112/tcp: 

```
frontend services
    bind *:80
    bind *:443
    mode http

    bind *:9990
    acl url_dcm4chee_dcm4chee-arc8080 path_beg /
    acl srcPort_dcm4chee_dcm4chee-arc80 dst_port 80
    acl url_dcm4chee_dcm4chee-arc9990 path_beg /
    acl srcPort_dcm4chee_dcm4chee-arc9990 dst_port 9990
    use_backend dcm4chee_dcm4chee-arc-be8080 if url_dcm4chee_dcm4chee-arc8080 srcPort_dcm4chee_dcm4chee-arc80
    use_backend dcm4chee_dcm4chee-arc-be9990 if url_dcm4chee_dcm4chee-arc9990 srcPort_dcm4chee_dcm4chee-arc9990

frontend tcpFE_11112
    bind *:11112
    mode tcp
    default_backend dcm4chee_dcm4chee-arc-be11112

backend dcm4chee_dcm4chee-arc-be11112
    mode tcp
    server dcm4chee_dcm4chee-arc dcm4chee_dcm4chee-arc:11112


backend dcm4chee_dcm4chee-arc-be8080
    mode http
    server dcm4chee_dcm4chee-arc dcm4chee_dcm4chee-arc:8080
backend dcm4chee_dcm4chee-arc-be9990
    mode http
    server dcm4chee_dcm4chee-arc dcm4chee_dcm4chee-arc:9990
```

frontend tcpFE_11112 and backend dcm4chee_dcm4chee-arc-be11112 were added manually. Then, I reload haproxy and everything works.

**Comment by vfarcic** [comment]
It should be fairly easy to allow multiple `reqMode` params. I'll be travelling today and tomorrow (back from DockerCon). I'll hope to have this implemented by Monday (if not before).

**Comment by vfarcic** [comment]
This feature turned out to be more complicated than I thought. I made some progress but did not manage to finish it. I hope to have it before the end of the week (if not before). Please let me know if that's OK.

**Comment by marceloaguero** [comment]
No problem Victor. I think this feature could be useful for many people.
If you need some testing or anything I can help, just let me know. Thanks!

**Comment by vfarcic** [comment]
@marceloaguero I made changes that I believe will solve this issue. However, I did not have time to test them on integration level so I did not make it public (yet). `reqMod` can now be specified with an index. Can you please do me a favor and try it out? If it works, I'll update the documentation and make an "official" release.

**Comment by marceloaguero** [comment]
I'm testing right now

**Comment by marceloaguero** [comment]
It works.
But there is a small issue in the haproxy configuration. The relevant parts of my docker-compose.yml files are the following.
For proxy stack:

```
version: "3"

services:

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
      - 9990:9990
      - 11112:11112
      - 2575:2575
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - BIND_PORTS=9990,11112,2575
    deploy:
      replicas: 1

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external: true
```

And for the service stack:

```
version: "3"
services:
...
  dcm4chee-arc:
  ...
  deploy:
      restart_policy:
        condition: on-failure
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath.1=/
        - com.df.port.1=8080
        - com.df.srcPort.1=80
        - com.df.reqMode.1=http
        - com.df.servicePath.2=/
        - com.df.port.2=9990
        - com.df.srcPort.2=9990
        - com.df.reqMode.2=http
        - com.df.servicePath.3=/
        - com.df.port.3=11112
        - com.df.srcPort.3=11112
        - com.df.reqMode.3=tcp
        - com.df.servicePath.4=/
        - com.df.port.4=2575
        - com.df.srcPort.4=2575
        - com.df.reqMode.4=tcp

networks:
  dcm4chee:
    external: false
  proxy:
    external: true
```

And the configuration for haproxy turns out to be:

```
...
frontend services
    bind *:80
    bind *:443
    mode http

    bind *:9990
    bind *:11112
    bind *:2575
    acl url_dcm4chee_dcm4chee-arc8080 path_beg /
    acl srcPort_dcm4chee_dcm4chee-arc80 dst_port 80
    acl url_dcm4chee_dcm4chee-arc9990 path_beg /
    acl srcPort_dcm4chee_dcm4chee-arc9990 dst_port 9990
    use_backend dcm4chee_dcm4chee-arc-be8080 if url_dcm4chee_dcm4chee-arc8080 srcPort_dcm4chee_dcm4chee-arc80
    use_backend dcm4chee_dcm4chee-arc-be9990 if url_dcm4chee_dcm4chee-arc9990 srcPort_dcm4chee_dcm4chee-arc9990

frontend tcpFE_11112
    bind *:11112
    mode tcp
    default_backend dcm4chee_dcm4chee-arc-be11112

frontend tcpFE_2575
    bind *:2575
    mode tcp
    default_backend dcm4chee_dcm4chee-arc-be2575


backend dcm4chee_dcm4chee-arc-be8080
    mode http
    server dcm4chee_dcm4chee-arc dcm4chee_dcm4chee-arc:8080
backend dcm4chee_dcm4chee-arc-be9990
    mode http
    server dcm4chee_dcm4chee-arc dcm4chee_dcm4chee-arc:9990
backend dcm4chee_dcm4chee-arc-be11112
    mode tcp
    server dcm4chee_dcm4chee-arc dcm4chee_dcm4chee-arc:11112
backend dcm4chee_dcm4chee-arc-be2575
    mode tcp
    server dcm4chee_dcm4chee-arc dcm4chee_dcm4chee-arc:2575
```

I think that     
```
    bind *:11112
    bind *:2575
```
shouldn't appear in the "frontend service" section.
