### ISSUE TITLE
ELK behind DFP

### ISSUE THREAD

**Issue by mborejdo** [vfarcic/docker-flow-proxy#225]
I am running an ELK stack in my swarm. I want the service to be available on two serviceDomains, proxying to different ports.
For example, I want kibana (port 5601) to be available on kibana.hostname and elasticsearch (port 9200) on elasticsearch.hostname.
I have tried different combinations of srcPort, port, etc, with no success.

My current stack config looks like this:

```
[...]
      labels:
        - com.df.notify=true
        - com.df.serviceDomain.1=kibana.hostname
        - com.df.port.1=5601
        - com.df.srcPort.1=80
        - com.df.serviceDomain.2=kibana.hostname
        - com.df.port.2=5601
        - com.df.srcPort.2=443
        - com.df.serviceDomain.3=elasticsearch.hostname
        - com.df.port.3=9200
        - com.df.srcPort.3=80
        - com.df.port.4=9200
        - com.df.srcPort.4=443
        - com.df.distribute=true
```

**Comment by leostarcevic** [comment]
Multiple domains should be separated with comma (,)
http://proxy.dockerflow.com/usage/

**Comment by mborejdo** [comment]
@leostarcevic I am exposing port 5601 and 9200 from one service. as far as I understand you need to use the "postfix"-notation (the docs seem to be here a bit unclear).
Using multiple serviceDomains for one service (and one destination port) works with a commaseperated list, though

**Comment by leostarcevic** [comment]
Ok, I'm not sure I understood the issue here, did your service labels got registered by dfp?
What does the /cfg/haproxy.cfg end up like inside the proxy service?

**Comment by leostarcevic** [comment]
You are right about the "postfix" - notation.. re-reading the docs:

Multiple destinations for a single service can be specified by adding index as a suffix to serviceDomain, srcPort, and port parameters. In that case, srcPort is required. Defining multiple destinations is useful in cases when a service exposes multiple ports with different paths and functions.

**Comment by mborejdo** [comment]
@leostarcevic currently I cannot share my full compose-yaml, since its very specific. I will try to prepare a stripped-down example.

Using these labels

```
      labels:
        - com.df.notify=true
        - com.df.serviceDomain=kibana.hostname
        - com.df.port=5601
        - com.df.srcPort=443
        - com.df.serviceDomain.2=elasticsearch.hostname
        - com.df.port.2=9200
        - com.df.srcPort.2=80
        - com.df.distribute=true
```

generates a haproxy.cfg like this
```
[...]
frontend services
    acl url_elastic_logstash5601 path_beg /
    acl srcPort_elastic_logstash443 dst_port 443
    acl domain_elastic_logstash hdr(host) -i kibana.hostname
    use_backend elastic_logstash-be5601 if url_elastic_logstash5601 domain_elastic_logstash srcPort_elastic_logstash443

[...]

backend elastic_logstash-be5601
    mode http
    log global
    server elastic_logstash elastic_logstash:5601

```

Suffixed dfp-labels seem to be ignored

**Comment by vfarcic** [comment]
@mborejdo Can you confirm that you're using service (not container) labels? Are they inside `deploy` section?

**Comment by mborejdo** [comment]
My full yml, redacted:

```
version: "3"

services:

  logstash:
    image: java8-logstash
    hostname: logstash
    healthcheck:
      test: "curl --fail http://127.0.0.1:9200 || exit 1"
      interval: 2m
      timeout: 60s
      retries: 5
    networks:
        - EM
    ports:
        - 12201:12201
        - 25826:25826
    environment:
        ES_JAVA_OPTS: "-Xms4G -Xmx4G"
    volumes:
      [...]
    deploy:
      placement:
        constraints:
          - node.labels.de.XXX.stability == testing
          - node.hostname == em-sv-dnodealpha
      labels:
        - com.df.notify=true
        - com.df.serviceDomain=kibana.XXX.de
        - com.df.port=5601
        - com.df.srcPort=443
        - com.df.serviceDomain.2=elasticsearch.XXX.de
        - com.df.port.2=9200
        - com.df.srcPort.2=80
        - com.df.distribute=true

networks:
  EM:
    external: true


```
