### ISSUE TITLE
Can DFP redirect request based on user agent?

### ISSUE THREAD

**Issue by sidikriyan** [vfarcic/docker-flow-proxy#233]
I want redirect all request from mobile phone to mobile-front-end, and default front-end will use desktop-front-end. Hope this feature will add soon. Thanks

**Comment by vfarcic** [comment]
I made a beta version with this feature. Can you please try it out using th e`vfarcic/docker-flow-proxy:beta` tag?

The following will be added to the documentation.

|Query        |Description                                                                     |Required|Default|
|-------------|--------------------------------------------------------------------------------|--------|-------|
|userAgent    |A comma-separated list of user agents. only requests with the same User-Agent will be forwarded to the backend. The parameter can be prefixed with an index thus allowing definition of multiple destinations for a single service (e.g. `userAgent.1`, `userAgent.2`, and so on).<br>Example: `googlebot,iphone`|No| |

**Comment by sidikriyan** [comment]
I already tested ```vfarcic/docker-flow-proxy:beta``` with  this command 

```
docker service create --name mobile-fe \
    --network proxy \
    --label com.df.notify=true \
    --label com.df.distribute=true \
    --label com.df.servicePath=/ \
    --label com.df.port=9090 \
    --label com.df.userAgent=android \
    localhost:5000/mobile-fe:latest
```

and this is generated haproxy.cfg

```
....
frontend services
    bind *:80
    bind *:443
    mode http

    acl url_mobile-fe9090 path_beg /
    acl user_agent_mobile-fe hdr(User-Agent) -i android
    use_backend mobile-fe-be9090 if url_mobile-fe9090 user_agent_mobile-fe

backend mobile-fe-be9090
    mode http
    server mobile-fe mobile-fe:9090
```

and I use that config in local and tested using `hdr(User-Agent)` and haproxy not redirecting request from android but if I use `hdr_sub(User-Agent)` it work.

**Comment by vfarcic** [comment]
`hdr` looks for the exact match while `hdr_sub` is looking for a substring. My guess is that the entrire `User-Agent` header was more than `android`.

Still, you are probably right about `hdr_sub` it should simplify the usage. I uploaded `vfarcic/docker-flow-proxy:beta2` image. Can you try it out and let me know whether it works in your scenario. I have tests that confirm that it works in scenarios I defined but it is always a good idea to see it through those defined by users.

**Comment by sidikriyan** [comment]
I try `vfarcic/docker-flow-proxy:beta2` but still not redirecting to `mobile-fe` if client use android or iphone. And it not remove back-end configuration in `haproxy.cfg` if i remove service from swarm.

I think the issue is on condition on haproxy configuration.

Me and my friend try some workaround on DFP for my case and this is works. Here `haproxy.cfg` that solve my case

```
frontend services
    bind *:80
    bind *:443
    mode http
    acl is_mobile hdr_sub(User-Agent) -i android iphone
    acl url_fe-desktop6060 path_beg /
    use_backend fe-desktop-be6060 if url_fe-desktop6060 !is_mobile
    acl url_fe-mobile9090 path_beg /
    use_backend fe-mobile-be9090 if url_fe-mobile9090 is_mobile

backend fe-desktop-be6060
    mode http
    server fe-desktop fe-desktop:6060


backend fe-mobile-be9090
    mode http
    server fe-mobile fe-mobile:9090
```

so this will redirecting request from mobile phone user agent to mobile front-end and desktop user agent to desktop front-end.

**Comment by vfarcic** [comment]
The config DFP creates is very similar (functionally the same) as the one you posted. Can you copy&paste the DFP config? That would help me locate the problem you're experiencing.

You can get DFP config by sending a [config request](http://proxy.dockerflow.com/usage/#config) if the proxy port 8080 is opened or by entering one of the proxy containers and outputting `/cfg/haproxy.cfg` file (e.g. `docker container exec -it [CONTAINER_ID] cat /cfg/haproxy.cfg`).

**Comment by vfarcic** [comment]
I made a few improvements to the code and some additional tests. I'm not sure whether they fix your problem (will know that when you send me your config file). I think you can be interested in the [Test_UserAgent_LastIndexCatchesAllNonMatchedRequests](https://github.com/vfarcic/docker-flow-proxy/blob/user-agent/integration_tests/integration_swarm_test.go#L157) test. It shows how to setup different destinations for two agents (amiga and amstrad). There is also a "catch-all" third destination that serves a similar function as `!is_mobile` from your example. If a match is not found with the first two destinations, the third one is used (as longs as, in the case of that test, the path matches).

Can you please double-check whether the improvements from the new beta release (`vfarcic/docker-flow-proxy:beta3`) fixes your problem (the latest changes were general, not directly related to your issue) or whether you configured your service incorrectly (compare it with the example from the test). If neither is true, please send me your config and, if possible, the stack you used.

**Comment by sidikriyan** [comment]
i will test `vfarcic/docker-flow-proxy:beta3` then give an update in this comment.. Thanks

**Comment by sidikriyan** [comment]
I use `dock-compose-stack` from DFP repo 

```
version: "3"

services:

  proxy:
    image: vfarcic/docker-flow-proxy:beta3
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      replicas: 2

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external: true
```

and this how i run my services : 

```
docker service create --name fe-adesktop \
    --network proxy \
    --label com.df.notify=true \
    --label com.df.distribute=true \
    --label com.df.servicePath=/ \
    --label com.df.port=6060 \
    localhost:5000/desktop-fe:latest
```

```
docker service create --name fe-mobile \
    --network proxy \
    --label com.df.notify=true \
    --label com.df.distribute=true \
    --label com.df.servicePath=/ \
    --label com.df.port=9090 \
    --label com.df.userAgent=android,iphone,ipad \
    localhost:5000/mobile-fe:latest
```
