### ISSUE TITLE
Ability to supply alternate haproxy.tmpl file to DFP

### ISSUE THREAD

**Issue by bsimpson53** [vfarcic/docker-flow-proxy#237]
At the moment to override the /cfg/tmpl/haproxy.tmpl you need to roll your own image which seems unnecessary.

One could mount a local file to do this, but if you're working with a multi-node swarm you would have to make sure that file was present on each machine.

By allowing the path to the template to be set with an environment variable one could for example use secrets (available on all hosts) to hold the template and do something like this:

```
version: "3.2"

services:

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - HAPROXY_TMPL_PATH=/run/secrets/haproxy.tmpl
      - MODE=swarm
    secrets:
      - cert
      - ca-file
      - source: myservice_dfdTemplateFe.tmpl
        target: mystack_myservice_dfdTemplateFe.tmpl
      - source: myservice_dfdTemplateBe.tmpl
        target: mystack_myservice_dfdTemplateBe.tmpl
      - haproxy.tmpl

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

secrets:
  cert-mydomain.io:
    file: ssl/mydomain.io.pem
  ca-file:
    file: ssl/ca-file.crt
  haproxy.tmpl:
    file: haproxy.tmpl
  mystack_myservice_dfdTemplateFe.tmpl:
    external: true
  mystack_myservice_dfdTemplateBe.tmpl:
    external: true
```

EDIT: I missed haproxy.tmpl from the secrets list

**Comment by bsimpson53** [comment]
Thinking about it, if I could just supply it as an option to docker-flow-proxy it would be fine:

```
/ # docker-flow-proxy --help
Usage:
  docker-flow-proxy [OPTIONS] <server>

Options:
  --haproxy-tmpl    Supply an alternate haproxy.tmpl file
  -h, --help             Show this help message

Available commands:
  server  Runs the server
```

**Comment by vfarcic** [comment]
Adding an environment variable like `HAPROXY_TMPL_PATH` should not be a problem. I can have it done before the end of the week. I'm not sure about doing the same through binary arguments since users are already used to use env. vars. for all general settings. On the other hand, it's easy to add both so I'll probably do that.

**Comment by vfarcic** [comment]
Failed tests

**Comment by vfarcic** [comment]
It's available as [release 1.381](https://github.com/vfarcic/docker-flow-proxy/releases/tag/1.381). Please try it out and let me know whether it works as expected.

**Comment by bsimpson53** [comment]
Hi, trying this out in 1.384

```
  proxy:
    image: vfarcic/docker-flow-proxy:1.384
    ports:
      - 80:80
      - 443:443
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - CFG_TEMPLATE_PATH=/run/secrets/haproxy.tmpl
      - MODE=swarm
    secrets:
      - cert-mydomian.io
      - ca-file
      - haproxy.tmpl
```

I was expecting DFP to use `/run/secrets/haproxy.tmpl` as the template to generate `/cfg/haproxy.cfg` from, but what happened was:

1. `/cfg/haproxy.cfg` was generated from `/cfg/tmpl/haproxy.tmpl`
2. haproxy was started using `/run/secrets/haproxy.tmpl` as its config file resulting in the following logs being written:

```
2017/05/22 11:28:11 Reloading the proxy
2017/05/22 11:28:11 Could not read the /var/run/haproxy.pid file
open /var/run/haproxy.pid: no such file or directory
```
