### ISSUE TITLE
Can't run docker registry:2 in proxy. Port 5000 doesn't seem to proxy anyting.

### ISSUE THREAD

**Issue by mbranchnl** [vfarcic/docker-flow-proxy#238]
I'm trying to run a private docker registry on my Docker Swarm environment (version 17.05), but it seems like that proxying to port 5000 fails for some reason.
Hereby my feedback:

Proxy setup:
```
version: "3"

services:

  proxy:
    image: vfarcic/docker-flow-proxy:latest
    ports:
      - 80:80
      - 443:443
      - 5000:5000
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      replicas: 1

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener:latest
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external: true
```

Registry setup:
```
version: '3.1'

services:
  registry:
      image: registry:2
      environment:
        - REGISTRY_HTTP_RELATIVEURLS=true
      deploy:
        labels:
          - com.df.notify=true
          - com.df.serviceDomain=registry.docker.mydomain.tld
          - com.df.port=5000
          - com.df.distribute=true
      networks:
        - proxy

networks:
  proxy:
    external: true
```

A **docker service ls** gives me feedback that port 5000 should be okay:
```
008shg82by9b        proxy_proxy            replicated          1/1                 vfarcic/docker-flow-proxy:latest            *:80->80/tcp,*:443->443/tcp,*:5000->5000/tcp
4fw2x81tuice        proxy_swarm-listener   replicated          1/1                 vfarcic/docker-flow-swarm-listener:latest
j1w21zu9lbdj        registry_registry      replicated          1/1                 registry:2
```

But trying to telnet on port 5000 (both with IP and hostname fails):
```
Trying 192.168.0.15... 
telnet: connect to address 192.168.0.15: Connection refused
```

Also pushing gives an error:
```
docker push registry.docker.mydomain.tld:5000/ubuntu                                                                                                                                                                                                                                                     
The push refers to a repository [registry.docker.mydomain.tld:5000/ubuntu]
Get https://registry.docker.mydomain.tld:5000/v1/_ping: dial tcp 149.210.158.209:5000: getsockopt: connection refused
```

Also doing a curl to http(s)://registry.docker.mydomain.tld:5000/v1/_ping fails on both protocols.


The logs in the swarm-listener and proxy seems okay, some snippets:
```

2017/05/12 12:57:11 Sending distribution request to http://10.0.0.3:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=5000&serviceDomain=registry.docker.mydomain.tld&serviceName=registry_registry
2017/05/12 12:57:11 Creating configuration for the service registry_registry
2017/05/12 12:57:11 Reloading the proxy
2017/05/12 12:57:11 Proxy config was reloaded
```

```
2017/05/12 12:48:35 Starting Docker Flow: Swarm Listener
2017/05/12 12:48:35 Starting iterations
2017/05/12 12:48:46 http: multiple response.WriteHeader calls
2017/05/12 12:51:45 Sending service created notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=5000&serviceDomain=registry.docker.mydomain.tld&serviceName=registry_registry
2017/05/12 12:56:51 Sending service removed notification to http://proxy:8080/v1/docker-flow-proxy/remove?distribute=true&serviceName=registry_registry
2017/05/12 12:57:11 Sending service created notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=5000&serviceDomain=registry.docker.mydomain.tld&serviceName=registry_registry
```

After that i've tried also another package that run's on port 5000 but that also fails, the package for port 5000 alternative was: https://github.com/getcarina/examples/tree/master/hello-world-app

with config:
```
version: '3'

services:

  registry:
    image: carinamarina/hello-world-app
    networks:
      - proxy
    deploy:
      placement:
        constraints: [node.role == manager]
      labels:
	- com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.serviceDomain=registry.docker.mydomain.tld
        - com.df.port=5000

networks:
  proxy:
    external: true
```

Same issue. When i'll stop exposing port 5000 through the proxy every thing works okay.
