### ISSUE TITLE
httpsOnly and serviceDomainMatchAll parameters

### ISSUE THREAD

**Issue by mcctomsk** [vfarcic/docker-flow-proxy#248]
I have several services through docker stack. One of them uses this parameters:
```
      labels:
        com.df.notify: "true"
        com.df.distribute: "true"
        com.df.aclName: "95-service-5"
        com.df.serviceDomainMatchAll: "true"
        com.df.servicePath: "/"
        com.df.httpsOnly: "true"
        com.df.serviceDomain: "foo.bar"
        com.df.port: "5000"
```
another one uses this:
```
   labels:
        com.df.notify: "true"
        com.df.distribute: "true"
        com.df.aclName: "40-service-6"
        com.df.servicePath: "/"
        com.df.serviceDomain: "subdomain.foo.bar"
        com.df.port: "5000"
```
In this configuration the subdomain.foo.bar service isn't accessible. When you try to open it via http protocol browser gets a redirection (302 code) to https but service doesn't support it.

Is it possible to fix this?
