### ISSUE TITLE
Support for SSL termination

### ISSUE THREAD

**Issue by wilkko** [vfarcic/docker-flow-proxy#25]
Tips and tricks how to handle HTTPS?

**Comment by wilkko** [comment]
To do SSL termination and reverse proxying with docker-flow-proxy in our environment, we would need to add ssl cert path and x-forwarded-proto to frontend section (or defaults) of the haproxy.cfg

haproxy.cfg
```
---
frontend http-https
    bind *:80
    **bind *:443 ssl crt /etc/ssl/private/dummy_server.pem
    http-request add-header x-forwarded-proto https if { ssl_fc }**
    option http-server-close
    acl url_dummy path_beg /dummy
    use_backend dummy-be if url_dummy

---
```

We could do SSL termination in front of docker-flow-proxy put the forwarded-for-proto header would be still missing.

**Comment by wilkko** [comment]
RFC 7239 now tries to standardize these well known headers. Suggesting to use the format specified in https://tools.ietf.org/html/rfc7239 as I would assume this will be accepted as a standard at some point.

```
Forwarded: for=192.0.2.60; proto=http; by=203.0.113.43
```

For Tomcat we can customize the headers but Jetty assumes `X-Forwarded-For` and `X-Forwarded-Proto` headers.

**Comment by vfarcic** [comment]
At the moment, the way to customize the base configuration is to create a new container. For example, Dockerfile could be:

```
FROM vfarcic/docker-flow-proxy
COPY haproxy.cfg /cfg/haproxy.cfg
```

You can see the current base configuration from https://github.com/vfarcic/docker-flow-proxy/blob/master/haproxy.tmpl .

Please let me know if you have a better suggestion how to customize the config. I'm open to any suggestion.

**Comment by mackeyja92** [comment]
Any examples of this working? About to give it a shot and wanted some guidance.

**Comment by vfarcic** [comment]
I won't be able to work on an example until the weekend. I hope that's OK.

**Comment by wilkko** [comment]
OK, did this succesfully with a Docker volume since our proxy servers are not in a cluster.

It seems that you have to override `/cfg/tmpl/haproxy.tmpl` and not `/cfg/haproxy.cfg` for it to work.

**Comment by wilkko** [comment]
Here's our Ansible script:

```
- name: launch Docker flow proxy container
  docker:
    image: "vfarcic/docker-flow-proxy:{{ proxy_version }}"
    name: 'proxy'
    state: "{{ container_state }}"
    hostname: "{{ container_hostname }}"
    restart_policy: "{{ container_restart_policy }}"
    net: default # https://github.com/ansible/ansible-modules-core/issues/1885
    env:
      CONSUL_ADDRESS: "{{ consul_location }}"
      PROXY_INSTANCE_NAME: "{{ container_hostname }}"
    links:
      - 'consul:consul'
    ports:
      - "{{ proxy_host_port }}:80"
      - "{{ proxy_host_ssl_port }}:443"
      - "{{ proxy_api_host_port}}:8080"
    volumes:
      - "{{ proxy_config_path }}/haproxy.tmpl:/cfg/tmpl/haproxy.tmpl"
      - "{{ proxy_ssl_cert_host_path }}:{{ proxy_ssl_cert_dest_path }}"
```
