### ISSUE TITLE
Using multiple ports/services

### ISSUE THREAD

**Issue by preinking** [vfarcic/docker-flow-proxy#250]
I'm trying to use df-proxy in front of a nexus instance that is now using 3 different ports/services (web, private registry and proxy to ducker hub)

So far I'm not able to figure out how I can create the following config without modifying the temple and building my own image (the listen section is hardcoded in the template)
 
listen registry
    bind *:8123,*:8124 ssl crt /run/secrets/cert.pem
    mode http
    redirect scheme https if !{ ssl_fc }
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    use-server srv1 if { dst_port 8123 }
    use-server srv2 if { dst_port 8124 }
    server srv1 dtg_nexus:18443
    server srv2 dtg_nexus:18444

frontend services
    bind *:80
    bind *:443 ssl crt /run/secrets/cert.pem
    mode http

   acl url_dtg_nexus8081 path_beg /
    acl domain_dtg_nexus hdr(host) -i nexus.lan.nl
    use_backend dtg_nexus-be8081 if url_dtg_nexus8081 domain_dtg_nexus

  nexus:
    image: sonatype/nexus3
    ports:
      - "8081:8081"
      - "18443:18443"
      - "18444:18444"
    networks:
      - default
      - proxy
    volumes:
      - /registry/nexus-data:/nexus-data
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=nexus.lan.nl
        - com.df.addReqHeader=X-Forwarded-Proto https if { ssl_fc }
        - com.df.port=8081
      placement:
        constraints: [node.role == manager]

**Comment by preinking** [comment]
Based on the documentation I would think that this request would be correct 

curl --noproxy "*" "http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port.1=18444&serviceDomain=nexus.lan.nl&serviceName=nexus&srcPort.1=8124"

It is however rejected 

{"Mode":"swarm","Status":"NOK","Message":"When MODE is set to \"service\" or \"swarm\", the port query is mandatory","ServiceName":"nexus","AclName":"","AddReqHeader":null,"AddResHeader":null,"BackendExtra":"","CheckResolvers":false,"ConnectionMode":"","ConsulTemplateBePath":"","ConsulTemplateFePath":"","DelReqHeader":null,"DelResHeader":null,"Distribute":true,"HttpsOnly":false,"HttpsPort":0,"IsDefaultBackend":false,"OutboundHostname":"","PathType":"","RedirectWhenHttpProto":false,"ReqRepReplace":"","ReqRepSearch":"","ReqPathReplace":"","ReqPathSearch":"","ServiceCert":"","ServiceDomain":["nexus.lan.nl"],"ServiceDomainMatchAll":false,"SetReqHeader":null,"SetResHeader":null,"SslVerifyNone":false,"TemplateBePath":"","TemplateFePath":"","TimeoutServer":"","TimeoutTunnel":"","Users":null,"XForwardedProto":false,"ServiceColor":"","ServicePort":"","AclCondition":"","FullServiceName":"","Host":"","LookupRetry":0,"LookupRetryInterval":0,"ServiceDest":[{"Port":"","ReqMode":"http","ReqModeFormatted":"","ServicePath":["/"],"SrcPort":0,"SrcPortAcl":"","SrcPortAclName":"","VerifyClientSsl":false,"UserAgent":{"Value":null,"AclName":""}}]}/ #

**Comment by vfarcic** [comment]
Hi,

Created two stacks; one for the proxy and the other for Nexus. The stacks are as follows.

proxy.yml
```
version: "3"

networks:

  proxy:
    external: true

services:

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
      - 8123:8123
      - 8124:8124
    networks:
      - proxy
    environment:
      - BIND_PORTS=8123,8124
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      replicas: 3

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]
```

nexus.yml
```
version: '3.1'

services:
  main:
    image: sonatype/nexus3
    networks:
      - proxy
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=${DOMAIN:-localhost}
        - com.df.servicePath.1=/
        - com.df.port.1=8081
        - com.df.srcPort.1=80
        - com.df.servicePath.2=/
        - com.df.port.2=18443
        - com.df.srcPort.2=8123
        - com.df.servicePath.3=/
        - com.df.port.3=18444
        - com.df.srcPort.3=8124

networks:
  proxy:
    external: true
```

The commands I executed are as follows.

```bash
docker network create --driver overlay proxy

docker stack deploy proxy.yml proxy

DOMAIN=localhost docker stack deploy -c nexus.yml nexus

# Wait until Nexus is up-and-running

curl -u admin:admin123 http://localhost/service/metrics/ping

# Returns `pong`
```

I did not know how to test the other two ports. It's been a while since the last time I used Nexus. Can you please let me know if you have the commands that I can use? Nexus3 Docker Hub page does not mention those ports.

Can you please use those stacks to create services and let me know whether it worked?
