### ISSUE TITLE
How to serve visualizer?

### ISSUE THREAD

**Issue by valeriomazzeo** [vfarcic/docker-flow-proxy#277]
It seems that reverse proxy is supported: https://github.com/dockersamples/docker-swarm-visualizer/issues/57

 but I can't figure out a way to serve it from:

`http://mydomain.com/visualizer`

--- Edit:

Just out of curiosity I tried with portainer too (https://portainer.readthedocs.io/en/stable/faq.html#how-can-i-configure-my-reverse-proxy-to-serve-portainer) and I am having similar issues.

**Comment by valeriomazzeo** [comment]
I managed with this configuration:

```
  visualizer:
    image: dockersamples/visualizer
    environment:
      - CTX_ROOT=/visualizer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      labels:
        com.df.notify: "true"
        com.df.distribute: "true"
        com.df.servicePath: "/visualizer"
        com.df.port: "8080"
```

Notice `CTX_ROOT` https://github.com/dockersamples/docker-swarm-visualizer/pull/70

Still having issues with portainer though.
