### ISSUE TITLE
503 page when postgres stack deployed

### ISSUE THREAD

**Issue by dave08** [vfarcic/docker-flow-proxy#285]
I deployed my proxy:
```
version: "3.1"

networks:
  proxy:
      driver: overlay
      external:
        name: proxy

services:
  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      replicas: 2

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]
```
Then my ci stack:

```
version: "3.1"

services:
  registry:
    image: registry:2.6.1
    ports:
      - "5000:5000"
    volumes:
      - registry:/var/lib/registry
    deploy:
      resources:
        reservations:
          memory: 100M

  master:
    image: jenkinsci/jenkins:${TAG:-lts-alpine}
    ports:
      - "50000:50000"
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    networks:
      - proxy
      - ci
    volumes:
      - jenkins:/var/jenkins_home
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/jenkins
        - com.df.port=8080

  agent:
    image: vfarcic/jenkins-swarm-agent
    environment:
      - USER_NAME_SECRET=/run/secrets/${JENKINS_USER_SECRET:-jenkins-user}
      - PASSWORD_SECRET=/run/secrets/${JENKINS_PASS_SECRET:-jenkins-pass}
      - COMMAND_OPTIONS=-master http://master:8080/jenkins -labels 'docker' -executors 5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /workspace:/workspace
    networks:
      - ci
    secrets:
      - jenkins-user
      - jenkins-pass
    deploy:
      mode: global

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

volumes:
  jenkins:
    external: true
  registry:
    external: true

networks:
  proxy:
    external: true
  ci:
    driver: overlay
```

And then my db stack:
```
version: '3.1'

services:
  postgresql-master:
    image: 'bitnami/postgresql:9.6'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=${PG_REPL_PASS:-repl_password}
      - POSTGRESQL_USERNAME=odoo
      - POSTGRESQL_PASSWORD=${PG_ODOO_PASS:-odoo_pass}
      - POSTGRESQL_DATABASE=odoo
    volumes:
      - postgres:/opt/bitnami/postgresql
    networks:
      - postgres
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.labels.role == db-master'
      resources:
        reservations:
          cpus: '1'
          memory: 1G
  postgresql-slave:
    image: 'bitnami/postgresql:9.6'
    networks:
      - postgres
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=${PG_REPL_PASS:-repl_password}
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    deploy:
      replicas: 1
      placement:
        constraints:
          - 'node.labels.role != db-master'
      resources:
        reservations:
          cpus: '.5'
          memory: 500M
  pgadmin:
    image: fenglc/pgadmin4:1.4
    networks:
      - postgres
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/pgadmin
        - com.df.port=5050
      placement:
        constraints:
          - 'node.labels.role != db-master'
volumes:
  postgres:
    external: true

networks:
  postgres:
    external: true

```
After deploying the ci stack, jenkins was available at /jenkins. After the db stack I got 503 page for /pgadmin and /jenkins, but the stats page was available. The service log for the proxy swarm listener:

proxy_swarm-listener.1.tnr5o7fvj10b@swarm-manager-02    | 2017/07/10 15:52:57 Retrying service created notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=8069&serviceName=core-services_odoo&servicePath=%2Fcrm
proxy_swarm-listener.1.tnr5o7fvj10b@swarm-manager-02    | 2017/07/10 15:53:02 Retrying service created notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=5050&serviceName=core-db_pgadmin&servicePath=%2Fpgadmin
proxy_swarm-listener.1.tnr5o7fvj10b@swarm-manager-02    | 2017/07/10 15:53:07 Retrying service created notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=8080&serviceName=ci_master&servicePath=%2Fjenkins
proxy_swarm-listener.1.tnr5o7fvj10b@swarm-manager-02    | 2017/07/10 15:53:28 Retrying service created notification to http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=8069&serviceName=core-services_odoo&servicePath=%2Fcrm
proxy_swarm-listener.1.tnr5o7fvj10b@swarm-manager-02    | 2017/07/10 15:53:38 ERROR: Request http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=8080&serviceName=ci_master&servicePath=%2Fjenkins returned status code 500
proxy_swarm-listener.1.tnr5o7fvj10b@swarm-manager-02    | {"Mode":"swarm","Status":"NOK","Message":"Could not send distribute request to the following addresses: [10.0.0.4 10.0.0.9]","ServiceName":"ci_master","AclName":"","AddReqHeader":null,"AddResHeader":null,"BackendExtra":"","CheckResolvers":false,"ConnectionMode":"","ConsulTemplateBePath":"","ConsulTemplateFePath":"","Debug":false,"DebugFormat":"","DelReqHeader":null,"DelResHeader":null,"Distribute":true,"HttpsOnly":false,"HttpsPort":0,"IsDefaultBackend":false,"OutboundHostname":"","PathType":"","ProxyMode":"","RedirectWhenHttpProto":false,"ReqPathReplace":"","ReqPathSearch":"","ServiceCert":"","ServiceDomainMatchAll":false,"SetReqHeader":null,"SetResHeader":null,"SslVerifyNone":false,"TemplateBePath":"","TemplateFePath":"","TimeoutServer":"","TimeoutTunnel":"","UseGlobalUsers":false,"Users":null,"XForwardedProto":false,"ServiceColor":"","ServicePort":"","AclCondition":"","DomainFunction":"","FullServiceName":"","Host":"","LookupRetry":0,"LookupRetryInterval":0,"ServiceDest":[{"IgnoreAuthorization":false,"Port":"8080","ReqMode":"http","ReqModeFormatted":"","ServiceDomain":[],"ServiceHeader":{},"ServicePath":["/jenkins"],"SrcPort":0,"SrcPortAcl":"","SrcPortAclName":"","VerifyClientSsl":false,"UserAgent":{"Value":null,"AclName":""}}]}
proxy_swarm-listener.1.tnr5o7fvj10b@swarm-manager-02    | 2017/07/10 15:53:38 ERROR: Request http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=5050&serviceName=core-db_pgadmin&servicePath=%2Fpgadmin returned status code 500
proxy_swarm-listener.1.tnr5o7fvj10b@swarm-manager-02    | {"Mode":"swarm","Status":"NOK","Message":"Could not send distribute request to the following addresses: [10.0.0.9 10.0.0.4]","ServiceName":"core-db_pgadmin","AclName":"","AddReqHeader":null,"AddResHeader":null,"BackendExtra":"","CheckResolvers":false,"ConnectionMode":"","ConsulTemplateBePath":"","ConsulTemplateFePath":"","Debug":false,"DebugFormat":"","DelReqHeader":null,"DelResHeader":null,"Distribute":true,"HttpsOnly":false,"HttpsPort":0,"IsDefaultBackend":false,"OutboundHostname":"","PathType":"","ProxyMode":"","RedirectWhenHttpProto":false,"ReqPathReplace":"","ReqPathSearch":"","ServiceCert":"","ServiceDomainMatchAll":false,"SetReqHeader":null,"SetResHeader":null,"SslVerifyNone":false,"TemplateBePath":"","TemplateFePath":"","TimeoutServer":"","TimeoutTunnel":"","UseGlobalUsers":false,"Users":null,"XForwardedProto":false,"ServiceColor":"","ServicePort":"","AclCondition":"","DomainFunction":"","FullServiceName":"","Host":"","LookupRetry":0,"LookupRetryInterval":0,"ServiceDest":[{"IgnoreAuthorization":false,"Port":"5050","ReqMode":"http","ReqModeFormatted":"","ServiceDomain":[],"ServiceHeader":{},"ServicePath":["/pgadmin"],"SrcPort":0,"SrcPortAcl":"","SrcPortAclName":"","VerifyClientSsl":false,"UserAgent":{"Value":null,"AclName":""}}]}
proxy_swarm-listener.1.tnr5o7fvj10b@swarm-manager-02    | 2017/07/10 15:53:59 ERROR: Request http://proxy:8080/v1/docker-flow-proxy/reconfigure?distribute=true&port=8069&serviceName=core-services_odoo&servicePath=%2Fcrm returned status code 500
proxy_swarm-listener.1.tnr5o7fvj10b@swarm-manager-02    | {"Mode":"swarm","Status":"NOK","Message":"Could not send distribute request to the following addresses: [10.0.0.9 10.0.0.4]","ServiceName":"core-services_odoo","AclName":"","AddReqHeader":null,"AddResHeader":null,"BackendExtra":"","CheckResolvers":false,"ConnectionMode":"","ConsulTemplateBePath":"","ConsulTemplateFePath":"","Debug":false,"DebugFormat":"","DelReqHeader":null,"DelResHeader":null,"Distribute":true,"HttpsOnly":false,"HttpsPort":0,"IsDefaultBackend":false,"OutboundHostname":"","PathType":"","ProxyMode":"","RedirectWhenHttpProto":false,"ReqPathReplace":"","ReqPathSearch":"","ServiceCert":"","ServiceDomainMatchAll":false,"SetReqHeader":null,"SetResHeader":null,"SslVerifyNone":false,"TemplateBePath":"","TemplateFePath":"","TimeoutServer":"","TimeoutTunnel":"","UseGlobalUsers":false,"Users":null,"XForwardedProto":false,"ServiceColor":"","ServicePort":"","AclCondition":"","DomainFunction":"","FullServiceName":"","Host":"","LookupRetry":0,"LookupRetryInterval":0,"ServiceDest":[{"IgnoreAuthorization":false,"Port":"8069","ReqMode":"http","ReqModeFormatted":"","ServiceDomain":[],"ServiceHeader":{},"ServicePath":["/crm"],"SrcPort":0,"SrcPortAcl":"","SrcPortAclName":"","VerifyClientSsl":false,"UserAgent":{"Value":null,"AclName":""}}]}
