### ISSUE TITLE
srcPort does not work

### ISSUE THREAD

**Issue by morph027** [vfarcic/docker-flow-proxy#293]
I'm trying to proxy an app with multiple ports using the indexed definitions (which worked last  time i've tried):

```
      labels:
        com.df.notify: "true"
        com.df.distribute: "true"
        com.df.servicePath.1: "/"
        com.df.port.1: "8082"
        com.df.srcPort.1: "8080"
        com.df.servicePath.2: "/"
        com.df.port.2: "8082"
        com.df.srcPort.2: "8082"
        com.df.servicePath.3: "/"
        com.df.port.3: "8084"
        com.df.srcPort.3: "8084"
        com.df.servicePath.4: "/"
        com.df.port.4: "8086"
        com.df.srcPort.4: "8086"
        com.df.serviceDomain: "foo.bar"
```

Proxy itself has `BIND_PORTS` set and swarm service config is exposing the ports too.

Resulting config looks ok to me (relevant parts only):

```
frontend services

    bind *:5000
    bind *:8082
    bind *:8084
    bind *:8086
    acl url_foobar_core8082 path_beg /
    acl srcPort_foobar_core8082 dst_port 8082
    acl domain_foobar_core8082 hdr(host) -i foo.bar
    acl url_foobar_core8082 path_beg /
    acl srcPort_foobar_core8082 dst_port 8082
    acl domain_foobar_core8082 hdr(host) -i foo.bar
    acl url_foobar_core8084 path_beg /
    acl srcPort_foobar_core8084 dst_port 8084
    acl domain_foobar_core8084 hdr(host) -i foo.bar
    acl url_foobar_core8086 path_beg /
    acl srcPort_foobar_core8086 dst_port 8086
    acl domain_foobar_core8086 hdr(host) -i foo.bar
    use_backend foobar_core-be8082 if url_foobar_core8082 domain_foobar_core8082 srcPort_foobar_core8082
    use_backend foobar_core-be8082 if url_foobar_core8082 domain_foobar_core8082 srcPort_foobar_core8082
    use_backend foobar_core-be8084 if url_foobar_core8084 domain_foobar_core8084 srcPort_foobar_core8084
    use_backend foobar_core-be8086 if url_foobar_core8086 domain_foobar_core8086 srcPort_foobar_core8086

backend foobar_core-be8082
    mode http
    server foobar_core foobar_core:8082
backend foobar_core-be8082
    mode http
    server foobar_core foobar_core:8082
backend foobar_core-be8084
    mode http
    server foobar_core foobar_core:8084
backend foobar_core-be8086
    mode http
    server foobar_core foobar_core:8086
```

The proxy always gives me 503 when accessing the proper urls like `http://foo.core:8082`

**Comment by morph027** [comment]
Looks like `srcPort` somehow breaks the acl matching (although it looks good to me)

Works:

```
services:
  nginx:
    image: "nginx:alpine"
    networks:
      - proxy
      labels:
        com.df.notify: "true"
        com.df.distribute: "true"
        com.df.servicePath: "/"
        com.df.port: "80"
        com.df.serviceDomain: "foo.bar"
```

Does not work.

```
services:
  nginx:
    image: "nginx:alpine"
    networks:
      - proxy
      labels:
        com.df.notify: "true"
        com.df.distribute: "true"
        com.df.servicePath: "/"
        com.df.port: "80"
        com.df.srcPort: "80"
        com.df.serviceDomain: "foo.bar"
```
