### ISSUE TITLE
Duplicate backend names

### ISSUE THREAD

**Issue by pomu0326** [vfarcic/docker-flow-proxy#300]
**Description**
I want to use a different serviceDomain with the same serviceName and port.

**My compose file**
```yaml
version: "3"

networks:

  proxy:
    external: true

services:

  proxy:
    deploy:
      replicas: 3
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - MODE=swarm
      - LISTENER_ADDRESS=swarm-listener
      - CONNECTION_MODE=${CONNECTION_MODE:-http-keep-alive}
    image: vfarcic/docker-flow-proxy:17.07.26-12

  swarm-listener:
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    image: vfarcic/docker-flow-swarm-listener

  gitlab:
    deploy:
      resources:
        limits:
          memory: 2G
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain.1=gitlab.mydomain.local
        - com.df.port.1=80
        - com.df.serviceDomain.2=mattermost.mydomain.local
        - com.df.port.2=80
        - com.df.ignoreAuthorization=true
    extra_hosts:
      - "gitlab.mydomain.local:127.0.0.1"
      - "mattermost.mydomain.local:127.0.0.1"
    networks:
      - proxy
    image: gitlab/gitlab-ce:9.4.1-ce.0
```

**Describe the results you received:**
haproxy have error. `[ALERT] 207/080944 (528) : Parsing [/cfg/haproxy.cfg:64]: backend 'gitlab_gitlab-be80' has the same name as backend 'gitlab_gitlab-be80' declared at /cfg/haproxy.cfg`

haproxy.cfg
```
frontend services
    bind *:80
    bind *:443
    mode http

    acl url_gitlab_gitlab80 path_beg /
    acl domain_gitlab_gitlab80 hdr(host) -i gitlab.mydomain.local
    acl url_gitlab_gitlab80 path_beg /
    acl domain_gitlab_gitlab80 hdr(host) -i mattermost.mydomain.local
    use_backend gitlab_gitlab-be80 if url_gitlab_gitlab80 domain_gitlab_gitlab80
    use_backend gitlab_gitlab-be80 if url_gitlab_gitlab80 domain_gitlab_gitlab80

backend gitlab_gitlab-be80
    mode http
    server gitlab_gitlab gitlab_gitlab:80
backend gitlab_gitlab-be80
    mode http
    server gitlab_gitlab gitlab_gitlab:80
```

**Describe the results you expected:**
haproxy.cfg
```
frontend services
    bind *:80
    bind *:443
    mode http

    acl url_gitlab_gitlab_1_80 path_beg /
    acl domain_gitlab_gitlab_1_80 hdr(host) -i gitlab.mydomain.local

    acl url_gitlab_gitlab_2_80 path_beg /
    acl domain_gitlab_gitlab_2_80 hdr(host) -i mattermost.mydomain.local

    use_backend gitlab_gitlab_1_be80 if url_gitlab_gitlab_1_80 domain_gitlab_gitlab_1_80
    use_backend gitlab_gitlab_2_be80 if url_gitlab_gitlab_2_80 domain_gitlab_gitlab_2_80

backend gitlab_gitlab_1_be80
    mode http
    server gitlab_gitlab gitlab_gitlab:80

backend gitlab_gitlab_2_be80
    mode http
    server gitlab_gitlab gitlab_gitlab:80
```
