### ISSUE TITLE
Latest build on docker hub yields incorrect haproxy config

### ISSUE THREAD

**Issue by alshabib** [vfarcic/docker-flow-proxy#303]
**Description**

Loading simple stack yaml file yields the following haproxy error:

```
/cfg # haproxy -f /cfg/haproxy.cfg -D -p /var/run/haproxy.pid -sf 10
[ALERT] 210/214002 (102) : parsing [/cfg/haproxy.cfg:52] : error detected in frontend 'services' while parsing redirect rule : error in condition: no such ACL : 'url_web_rest8080'.
[ALERT] 210/214002 (102) : Error(s) found in configuration file : /cfg/haproxy.cfg
[ALERT] 210/214002 (102) : Fatal errors found in configuration.
```

with this yaml file:

```
version: "3.3"

services:

  webui:
    image: nginx
    networks:
      - proxy
    deploy:
      labels:
        - com.df.httpsOnly=true
        - com.df.redirectWhenHttpProto=true
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/
        - com.df.port=80

  rest:
    image: some-other-container
    networks:
      - proxy
    deploy:
      labels:
        - com.df.httpsOnly=true
        - com.df.redirectWhenHttpProto=true
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/api
        - com.df.port=8080

networks:
  proxy:
    driver: overlay
    external: true
```

**Steps to reproduce the issue:**
Assuming running swarm with dfp and swarm-listener.

1. docker stack deploy -c stack-file.yml web
2. docker service logs -f proxy_proxy
3. Observe dfp not reconfiguring correctly

**Describe the results you received:**

Unable to reach my services. dfp had following error.

```
/cfg # haproxy -f /cfg/haproxy.cfg -D -p /var/run/haproxy.pid -sf 10
[ALERT] 210/214002 (102) : parsing [/cfg/haproxy.cfg:52] : error detected in frontend 'services' while parsing redirect rule : error in condition: no such ACL : 'url_web_rest8080'.
[ALERT] 210/214002 (102) : Error(s) found in configuration file : /cfg/haproxy.cfg
[ALERT] 210/214002 (102) : Fatal errors found in configuration.
```

**Describe the results you expected:**

dfp reconfig and being able to reach my services.

**Additional information you deem important (e.g. issue happens only occasionally):**

Reverted to dfp version 17.07.20-7 and everything worked out of the box and as expected.
