### ISSUE TITLE
HAproxy templates for non-docker services

### ISSUE THREAD

**Issue by Benster900** [vfarcic/docker-flow-proxy#316]
**Description**

Dockerfile:
```
FROM vfarcic/docker-flow-proxy:17.08.16-25
ADD services-fe.tmpl /cfg/tmpl/
ADD services-be.tmpl /cfg/tmpl/
```

services-fe-tmpl:
```
acl url_example hdr(host) -i test.example.com
use_backend example_backend if url_example
```

services-be.tmpl:
```
backend example_backend
    mode http
    server test 192.168.1.1:80 check
```

docker-compose.ym
```
version: "3.1"
services:
  proxy:
    image: $CONTAINER_RELEASE_IMAGE (Used by Gitlab to deploy)
    ports:
      - 60080:80
    networks:
      - proxy
      - test-net
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - DFP_SERVICE_1_TEMPLATE_FE_PATH=/cfg/tmpl/services-fe.tmpl
      - DFP_SERVICE_1_TEMPLATE_BE_PATH=/cfg/tmpl/services-be.tmpl
      - MODE=swarm
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 1250M
        reservations:
          cpus: '0.95'
          memory: 1525M
      restart_policy:
        condition: any
        delay: 15s
      update_config:
        parallelism: 1
        delay: 60s
      placement:
        constraints:
          - node.role == manager
          - node.labels.type == proxy
      labels:
        - com.df.serviceDomain=example.com
        - com.df.notify=true

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener:17.07.28-1
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 1250M
        reservations:
          cpus: '0.001'
          memory: 10M
      restart_policy:
        condition: any
        delay: 15s
      update_config:
        parallelism: 1
        delay: 60s
      placement:
        constraints:
          - node.role == manager
          - node.labels.type == proxy
      labels:
        - com.df.distribute=true

  #### This container is used for testing the proxy ####
  whoami:
    image: jwilder/whoami
    networks:
      - tools-net
    deploy:
      replicas: 2
      labels:
        - com.df.notify=true
        - com.df.port=8000
        - com.df.serviceDomain=whoami.indeed.net
        - com.df.reqPathReplace=/

networks:
  proxy:
    external: true
 test-net:
    external: true
```

**Describe the results you received:**
I can hit whomai.example.com but I am not able to route to test.example.com a non-docker service behind the proxy.

**Describe the results you expected:**
I would like to add non-docker services to HAproxy templates and reload the container.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker Swarm
