### ISSUE TITLE
HAProxy config generated using reqMode=sni not correct

### ISSUE THREAD

**Issue by jpalpant** [vfarcic/docker-flow-proxy#320]
This is my first ever bug report on a OS project, so I hope I can be descriptive and helpful. I'm available for dialogue and clarification as needed. I've written... a lot. For anyone who comes along later to see this issue. I'm available for discussion or more information too - and I've tried to obscure the exact details of the website I'm deploying, but if I missed any place please let me know.

**Description**
I am attempting to use docker-flow-proxy with Docker Swarm. I need to proxy several kinds of services: plain http, https with SSL termination, and https with SSL passthrough. The first two I could configure, but for the last one I cannot get a working HAProxy config.

**Steps to reproduce the issue:**
1. Use docker stack deploy to deploy a standard docker-flow-proxy + docker-flow-swarm-listener. I expose port 8080 of docker-flow-proxy service in order to query the HAProxy configuration. 80, 443, and 1669 will be my http, https, and https+ssl passthrough ports. I don't specify a tag, but docker inspect on the proxy container says I'm using "Image": "sha256:6365ff9a8c8d00fcfa1267a45ceebaa76a1477cb6cb1acbebfa21f01ac9c6519", if that can help identify exact version for future reference. The tag on the pulled image is latest.

docker-compose.yml:
```
version: "3.3"
services:
  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 8080:8080
      - 9080:80
      - 9443:443
      - 9669:1669
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - DEBUG=true
    deploy:
      replicas: 1

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  proxy:
    external: true

```
2. Use docker stack deploy to deploy another docker service that will serve as an HTTPS backend. This backend is essentially a dumb nginx container that accepts cert and key through secrets and then serves static content. I expose the SSL port of the service in order to test directly connecting, around the proxy.
**docker-compose.yml using reqMode=sni:**
```
version: "3.3"
services:
  web:
    image: my-website-image
    networks:
      - proxy
    ports:
      - 8443:443
    secrets:
      - website-ssl-key
      - website-ssl-cert
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=my.ssl.domain
        - com.df.port=443
        - com.df.srcPort=1669
        - com.df.reqMode=sni

networks:
  proxy:
    external: true

secrets:
  website-ssl-key:
    external: true
  website-ssl-cert:
    external: true
```
  
**Describe the results you received:**
HAProxy configuration via curl localhost:8080/v1/docker-flow-proxy/config:
```
global
    pidfile /var/run/haproxy.pid
    tune.ssl.default-dh-param 2048
    log 127.0.0.1:1514 local0

    # disable sslv3, prefer modern ciphers
    ssl-default-bind-options no-sslv3
    ssl-default-bind-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

    ssl-default-server-options no-sslv3
    ssl-default-server-ciphers ECDH+AESGCM:DH+AESGCM:ECDH+AES256:DH+AES256:ECDH+AES128:DH+AES:RSA+AESGCM:RSA+AES:!aNULL:!MD5:!DSS

resolvers docker
    nameserver dns 127.0.0.11:53

defaults
    mode    http
    balance roundrobin

    option  http-keep-alive
    option  forwardfor
    option  redispatch

    errorfile 400 /errorfiles/400.http
    errorfile 403 /errorfiles/403.http
    errorfile 405 /errorfiles/405.http
    errorfile 408 /errorfiles/408.http
    errorfile 429 /errorfiles/429.http
    errorfile 500 /errorfiles/500.http
    errorfile 502 /errorfiles/502.http
    errorfile 503 /errorfiles/503.http
    errorfile 504 /errorfiles/504.http

    maxconn 5000
    timeout connect 5s
    timeout client  20s
    timeout server  20s
    timeout queue   30s
    timeout tunnel  3600s
    timeout http-request 5s
    timeout http-keep-alive 15s

frontend services
    bind *:80
    bind *:443
    mode http

    option httplog
    log global

frontend service_1669
    bind *:1669
    mode tcp
    tcp-request inspect-delay 5s
    tcp-request content accept if { req_ssl_hello_type 1 }
    acl sni_website_web443-1 path_beg /
    acl srcPort_website_web1669 dst_port 1669
    use_backend website_web-be443_0 if sni_website_web443-1 srcPort_website_web1669

backend website_web-be443_0
    mode tcp
    log global
    server website_web website_web:443

```
cURL test - I am using /etc/hosts to identify the my.ssl.domain domain name as 127.0.0.1, and 9669 because that is the published port for the service that should point back to the TCP port 1669 on the docker-flow-proxy service:
```
bash-3.2$ curl -iv https://my.ssl.domain:9669
* Rebuilt URL to: https://my.ssl.domain:9669/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to my.ssl.domain (127.0.0.1) port 9669 (#0)
* Server aborted the SSL handshake
* Closing connection 0
curl: (35) Server aborted the SSL handshake
```

HAProxy tcp log message:
No log for the attempted TCP connection, even though I set DEBUG=true it seems the option tcplog log global setting is not added to the frontend service

**Describe the results you expected:**
The end result should be the ability to connect to the backend service through the port exposed on the proxy. Testing the backend directly through it's exposed port with cURL looks like this:
```
bash-3.2$ curl -iv https://my.ssl.domain:8443
* Rebuilt URL to: https://my.ssl.domain:8443/
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to my.ssl.domain (127.0.0.1) port 8443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate: my.ssl.domain
* Server certificate: Let's Encrypt Authority X3
* Server certificate: DST Root CA X3
> GET / HTTP/1.1
> Host: my.ssl.domain:8443
> User-Agent: curl/7.54.0
> Accept: */*
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
```

The difference being that I should be able to change that to port 9669 and have the TCP connection go through HAProxy

I've also tried to do this using HAProxy directly with a manual configuration and I can get it to work. I can use a docker image built with this dockerfile:
```
FROM haproxy:latest
LABEL maintainer Justin Palpant <justin@palpant.us>
COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
```

Using this haproxy.cfg:
```
# Adjust the timeout to your needs
defaults
  timeout client 30s
  timeout server 30s
  timeout connect 5s
 
# Single VIP 
frontend ft_ssl_vip
  bind :1669
  mode tcp
 
  tcp-request inspect-delay 5s
  tcp-request content accept if { req_ssl_hello_type 1 }
 
  use_backend bk_ssl_application_1 if { req.ssl_sni -i my.ssl.domain }
 
# Application 1 farm description
backend bk_ssl_application_1
  mode tcp
  server server1 web:443

```
I took this configuration from the HAProxy example here: https://www.haproxy.com/blog/enhanced-ssl-load-balancing-with-server-name-indication-sni-tls-extension/

And I deployed it by updating the docker-compose.yml file used to deploy my backend web server to this:
```
version: "3.3"
services:
  haproxy:
    image: myhaproxy
    networks:
      - proxy
    ports:
      - 10669:1669
    deploy:
      mode: replicated
      replicas: 1

  web:
    image: my-website-image
    networks:
      - proxy
    ports:
      - 8443:443
    secrets:
      - website-ssl-key
      - website-ssl-cert
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=my.ssl.domain
        - com.df.port=443
        - com.df.srcPort=1669
        - com.df.reqMode=sni

networks:
  proxy:
    external: true

secrets:
  website-ssl-key:
    external: true
  website-ssl-cert:
    external: true

```  
HAProxy can resolve the backend web:443 because the service is deployed in the same stack as the backend web server. With this custom HAProxy-configuration I am able to do the cURL test to port 10669 and be routed to the correct backend using SNI. That means a request to https://localhost:10669 fails (unexpected close), but https://my.ssl.domain:10669 will connect

**Additional information you deem important (e.g. issue happens only occasionally):**
Differences between the working HAProxy configuration and the one generated by docker-flow-proxy:
1) docker-flow-proxy configuration includes an ACL with path_beg - I don't know what effect that might have, but it doesn't make much sense to me to use path_beg in the context of a TLS connection, the proxy should never see the path requested.
2) docker-flow-proxy configuration does not include an ACL using req.ssl_sni -i {serviceDomain}, which means SNI-based routing is not possible

For all I've written, these are probably pretty simple fixes to the template for SNI and the tests, right? I think the problem is in getFrontTemplateSNI in proxy/ha_proxy.go, but I have no golang experience and don't really know how to edit it - I can barely even figure out where the strings end. I could probably manage if I could learn to do linting (go fmt or something like that?) and run the unit tests locally, but it would be my first golang foray.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Docker Swarm with a single manager node running using Docker for Mac
```
bash-3.2$ docker version
Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:31:53 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:51:55 2017
 OS/Arch:      linux/amd64
 Experimental: true

bash-3.2$ curl --version
curl 7.54.0 (x86_64-apple-darwin16.0) libcurl/7.54.0 SecureTransport zlib/1.2.8
```
