### ISSUE TITLE
Trying to put registry inside swarm behind flow-proxy

### ISSUE THREAD

**Issue by aleskinen** [vfarcic/docker-flow-proxy#338]
My docker-compose.yml is this:
version: '3.1'
services:
  registry:
    image: registry:2.6
    environment:
      REGISTRY_HTTP_ADDR: "registry.tek.fi:443"
   secrets:
      - cert-star_tek_fi.pem
    volumes:
      - registry:/var/lib/registry
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=registry.tek.fi
        - com.df.port=443
        - com.df.srcPort=443
        - com.df.httpsOnly=true
        - com.df.servicePath=/
        - com.df.reqMode=tcp
      placement:
        constraints: [node.labels.registry==true]
    networks:
      - proxy
networks:
  proxy:
    external: true
volumes:
  registry:
    external: true
secrets:
  cert-star_tek_fi.pem:
        file: /etc/docker/certs.d/star_tek_fi.pem

docker service logs core_registry:
core_registry.1.1uuoc4wy7rv2@dca.tek.fi    | time="2017-09-29T12:18:43Z" level=warning msg="No HTTP secret provided - generated random secret. This may cause problems with uploads if multiple registries are behind a load-balancer. To provide a shared secret, fill in http.secret in the configuration file or set the REGISTRY_HTTP_SECRET environment variable." go.version=go1.7.6 instance.id=4e012ee6-e0da-4db9-b4fe-fa7d27b109b8 version=v2.6.2 
core_registry.1.1uuoc4wy7rv2@dca.tek.fi    | time="2017-09-29T12:18:43Z" level=info msg="redis not configured" go.version=go1.7.6 instance.id=4e012ee6-e0da-4db9-b4fe-fa7d27b109b8 version=v2.6.2 
core_registry.1.1uuoc4wy7rv2@dca.tek.fi    | time="2017-09-29T12:18:43Z" level=info msg="Starting upload purge in 5m0s" go.version=go1.7.6 instance.id=4e012ee6-e0da-4db9-b4fe-fa7d27b109b8 version=v2.6.2 
core_registry.1.tjhpebt4u6pk@dca.tek.fi    | time="2017-09-29T12:18:37Z" level=info msg="using inmemory blob descriptor cache" go.version=go1.7.6 instance.id=ce1f0efa-07ae-4d82-93c0-8aca52c84ba5 version=v2.6.2 
core_registry.1.1uuoc4wy7rv2@dca.tek.fi    | time="2017-09-29T12:18:43Z" level=fatal msg="listen tcp 194.100.213.87:443: bind: cannot assign requested address" 

Duplicate log lines have been removed. Docker flow proxy is in default configration. Any help appreciated.

**Comment by patrickleet** [comment]
Hey, I don't have a cert on my registry, but viktor had an example of terminating ssl at the proxy, so if that works for your need you can accomplish like this:

```
version: '3.2'

services:

  main:
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - registry:/var/lib/registry
    networks:
      - proxy
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=5000
        - com.df.serviceDomain=${REGISTRY_DOMAIN}
        - com.df.xForwardedProto=true
        - com.df.letsencrypt.host=${REGISTRY_DOMAIN}
        - com.df.letsencrypt.email=${LETS_ENCRYPT_EMAIL}
      resources:
        reservations:
          memory: 100M
        limits:
          memory: 200M

volumes:

  registry:
    driver: cloudstor:aws
    external: false

networks:

  proxy:
    external: true

```
