### ISSUE TITLE
Deploying a stack with a service having replicas: 0 makes dfp fail over and over

### ISSUE THREAD

**Issue by jotunskij** [vfarcic/docker-flow-proxy#344]
**Description**

Deploying a service with 0 replicas when running in swarm mode causes haproxy to fail and DFP to continously restart.

**Steps to reproduce the issue:**
1. Create a local docker swarm
2. Run the docker stack version of dfp provided on the homepage
3. Deploy the following stack:
```yaml
version: '3'

services:
  nginx:
    image: nginx:1.13-alpine
    ports:
      - 80
    networks:
      - proxy
      - default
    deploy:
      replicas: 0
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/nginx
        - com.df.port=80
        - com.df.reqPathReplace=/
        - com.df.reqPathSearch=/nginx

networks:
  default:
    external: false
  proxy:
    external: true
```

**Describe the results you received:**
DFP will continously fail while retrying load of configuration. Central part of log:
```
dfp_proxy.1.syb83c79xwc8@moby    | (BADINDEX)    server nginx_nginx nginx_nginx:80
dfp_proxy.1.syb83c79xwc8@moby    | 2017/10/05 04:11:59 Config validation failed
dfp_proxy.1.syb83c79xwc8@moby    | [ALERT] 277/041159 (1630) : parsing [/cfg/haproxy.cfg:61] : 'server nginx_nginx' : could not resolve address 'nginx_nginx'.
dfp_proxy.1.syb83c79xwc8@moby    | [ALERT] 277/041159 (1630) : Failed to initialize server(s) addr.
```

**Describe the results you expected:**
Services with replicas set to 0 should proabably not be included in the haproxy configuration I presume.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional environment details (AWS, VirtualBox, physical, etc.):**
Running on local machine, MacOS 10.12.6 (16G29), Docker version 17.09.0-ce, build afdb6d4
