### ISSUE TITLE
You cannot create service named "proxy"

### ISSUE THREAD

**Issue by LorenzoLuconi** [vfarcic/docker-flow-proxy#345]
In my docker swarm instance I have a service configured like this:

```
version: '3'

services:
 proxy:
  image: nginx:stable-alpine
  hostname: nginx
  networks:
    - proxy

networks:
  proxy:
    external: true
```

This is not, obviously, a DFP instance, but after I started my service, my DFP begins to call this service for distribution. After a lot of test, I realize that my service is called by DFP because his name is "proxy". I deployed it as service inside a stack so the service name is something like "app_proxy", but DFP discover it and use it for distribution.
When DFP server doesn't answer to distribution request (like mine NGINX), the DSL receives an error and so it tries many times to add/remove the new configuration.

Probably this behavior is documented but I didn't find it.  Anyway I don't think is a good idea to look for other DFP instances looking for name "proxy": you probably need something to register your instances or at least a label. 

Lorenzo

**Comment by vfarcic** [comment]
You should modify *Docker Flow Swarm Listener (DFSL)* and *Docker Flow Proxy (DFP)* service definition.

## DFSL

Change `DF_NOTIFY_CREATE_SERVICE_URL` and `DF_NOTIFY_REMOVE_SERVICE_URL` env. vars. Even though DFSL is often used together with DFP, it is designed to work as a notifier for any service. Those two env. vars. provide addresses DFSL uses to send requests. If, for example, DFP service is called `app_proxy`, the env. vars. would be:

```
DF_NOTIFY_CREATE_SERVICE_URL=http://app_proxy:8080/v1/docker-flow-proxy/reconfigure
DF_NOTIFY_REMOVE_SERVICE_URL=http://app_proxy:8080/v1/docker-flow-proxy/remove
```

You can find more info in http://swarmlistener.dockerflow.com/config/

## DFP

Change `SERVICE_NAME` env .var. If you're DFP service is called `app_proxy`, the env. var. would be:

```
SERVICE_NAME=app_proxy
```

More info is in http://proxy.dockerflow.com/config/


Please let me know if this answers your questions.

**Comment by LorenzoLuconi** [comment]
Thank you for your reply. Sorry but I'm not sure you answered to my question, maybe I'm not being clear (my english is not good enough). I try to explain again what I found.

This is my configuration for docker flow proxy stack:

```
version: "3"

services:

  proxy:
    image: vfarcic/docker-flow-proxy:17.10.01-35
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      replicas: 1

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener:17.09.30-13
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external: true
```

I deployed this stack with the name "flow" so I have flow_proxy e flow_swarm-listener and all services work as expected.

I have many other services/stacks and one of them need a special reverse proxy (nginx). This is an example of the configuration:

```
version: '3'

services:
 myapp:
  image: myapp
  networks:
   - default

 proxy:
  image: myadpp-nginx
  networks:
    - proxy
    - default
  deploy:
    labels:
     - com.df.notify=true
     - com.df.distribute=true
     - com.df.servicePath=/
     - com.df.serviceDomain=myapp.mydomain.com
     - com.df.port=80

networks:
  proxy:
    external: true
  default:
```

This stack is deployed as "app" so I have two new services: app_proxy and app_myapp.
After the deploy of this stack my DFP (flow_proxy service) write these log in console (many times every 5 seconds until max retries):

```
2017/10/06 09:30:43 Sending distribution request to http://10.0.0.23:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=80&replicas=1&serviceDomain=myapp.mydomain.com&serviceName=test_proxy&servicePath=%2F
2017/10/06 09:30:48 Sending distribution request to http://10.0.0.3:8080/v1/docker-flow-proxy/reconfigure?distribute=false&port=80&replicas=1&serviceDomain=myapp.mydomain.com&serviceName=test_proxy&servicePath=%2F
```

Please note 10.0.0.3 is the ip address of flow_proxy  service (my DFP) and 10.0.0.23 is the ip address of the just created service "app_proxy" (nginx not a DFP).

So it looks like the DFP try to send distribution request to any service named proxy (*_proxy).

If I change the name of the "proxy" service to "nginx":

```
...
 nginx:
  image: nginx:stable-alpine
  hostname: nginx
  networks:
    - proxy
    - default
  deploy:
    labels:
     - com.df.notify=true
     - com.df.distribute=true
     - com.df.servicePath=/
     - com.df.serviceDomain=myapp.mydomain.com
     - com.df.port=80

...
```

the service is deployed with name app_nginx instead of app_proxy and the problem disappear.
I hope I have been clearer now.

Thank you for your support.
Lorenzo

**Comment by vfarcic** [comment]
Your current DFSL service definition is:

```
 swarm-listener:
    image: vfarcic/docker-flow-swarm-listener:17.09.30-13
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]
```

Through `DF_NOTIFY_*` env. vars. you're telling DFSL to send notifications to DFP running on service name `proxy`. Docker Swarm allows you to use both short (`proxy`) and long (`flow_proxy`) service names. Since you have two services named `proxy` (in different stacks), requests are going to both. If you change env. vars. to:

```
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://flow_proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://flow_proxy:8080/v1/docker-flow-proxy/remove
```

... you'd identify DFP with a long and unique name and there would be no mix-ups.

Please let me know if that answered your question. I have a feeling that I'm still misunderstanding your issue. Maybe you can ping me on our Slack channel `devops20.slack.com` and we can have a talk instead? If you're not already registered, you can do so through [slack.devops20toolkit.com](http://slack.devops20toolkit.com).

**Comment by LorenzoLuconi** [comment]
In *server/util.go* (https://github.com/vfarcic/docker-flow-proxy/blob/master/server/util.go) you find out other instances of the DFP service using name lookup:

```go
dns := fmt.Sprintf("tasks.%s", proxyServiceName)
// ....
lookupHost(dns)
```
In docker swarm stack configuration (http://proxy.dockerflow.com/swarm-mode-stack/) you define two services: "proxy" and "swarm-listener" both connected to the same overlay network called "proxy". The service name of DFP  is "proxy" so a lookupHost("tasks.proxy") is executed. With this lookup you get all IP addresses of service named "proxy" **inside the same network**. Because I defined a service, connected to the same network, named "proxy" (names collision), your DFP server finds two IP address: himself and my service (not a DFP) and tries to redistribute the configuration to both. This is an example of name resolution inside the docker swarm with a ranning DFP service (10.0.0.23) and another service (10.0.0.3):

```bash
# dig tasks.proxy

; <<>> DiG 9.10.4-P8 <<>> tasks.proxy
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37175
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;tasks.proxy.			IN	A

;; ANSWER SECTION:
tasks.proxy.		600	IN	A	10.0.0.23
tasks.proxy.		600	IN	A	10.0.0.3
```
I think there is a problem in your architecture and only DFSL should distribute the configuration, anyway this can be a topic for another thread.

Finally, to avoid names collision, I suggest you to change the docker swarm stack configuration renaming the DFP "proxy" service to something less common like "swarm-proxy" or "flow-swarm-proxy":

```yml
version: "3"

services:

  swarm-proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - SERVICE_NAME=swarm-proxy
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      replicas: 2

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://swarm-proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://swarm-proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external: true
```

And (or) warn users to not create any service with the same name of the DFP.
