### ISSUE TITLE
Feature request: Redirect to https for X-Forwarded-Proto not set or not https

### ISSUE THREAD

**Issue by andrh** [vfarcic/docker-flow-proxy#351]
Use case: 

When running D4AWS you can use Certificate Manager to create a certificate and have D4AWS set up listeners for the protocol HTTPS that terminates SSL in ELB. There is however no way to set up an HTTP listener in the ELB, only TCP, thus for incoming requests X-Forwarded-Proto is not set. Redirecting http traffic to https can't be done since communication between ELB and proxy is always http, so normal redirection causes redirect from https to https and the flag `redirectWhenHttpProto ` can't be used since X-Forwarded-Proto is not set for http requests.

Suggested solution:
Create a queryParameter for redirecting to HTTPS whenever the X-Forwarded-Proto header is absent or set to anything else than `https`. 

It would also be nice if there were some way to specify redirect code so that it can be set to 301 as for HTTPS_ONLY.

**Comment by carl-utter** [comment]
@andrh - we have our cluster's df-proxy configured to cover http-to-https scenarios (which is what it sounds like you are asking for?) using the following service labels in the docker-flow-proxy.yml file:

```yaml
services:
    proxy:
        image: vfarcic/docker-flow-proxy:${TAG:-latest}
        labels:
          ...
          - com.df.redirectWhenHttpProto=true
          - com.df.httpsOnly=true
          - com.df.httpsRedirectCode=301
         ...
```

**Referenced Here:** [https://proxy.dockerflow.com/usage/#http-mode-query-parameters](url)

_**NOTE:** We also add the "com.df.httpsOnly=true" service label to any service(s) within the cluster which produces http traffic that is destined to become an inbound request to the cluster's proxy again._
