### ISSUE TITLE
Problems using same domain but different paths in two containers

### ISSUE THREAD

**Issue by V1ct0rV** [vfarcic/docker-flow-proxy#361]
**Description**

Hi,

The problem is I have 2 services using same domain, the first service has `com.df.servicePath=/` the second one `com.df.servicePath=/orchestrator/,/hub/`, I want all request to the domain go to `service1`, but the resquests to the paths `/orchestrator` or `/hub` go to `service2`, this configuration was working good monts ago (I remember I need to restart the proxy or event the docker service a couple times because was not working) but I deploy a new server today and stop working, I restarted the services, docker service, the physical machine with no luck,, only one time I got working, but, after another services deploy and reconfiguration stop working.

This is my compose file (I do not put real information, but the labels are the real ones)

```
version: "3"

services:
  service-one:
    image: miproduct:develop
    environment:
      - ENVIRONMENT=Staging
    networks:
      - proxy_public
    deploy:
      replicas: 3
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=staging.midomain.com
        - com.df.servicePath=/
        - com.df.port=5000
        - com.df.users=user:P@ss...,user1:P@ss...
        - com.df.setReqHeader=X-Via %[env(HOSTNAME)],X-Username %[http_auth_group(stack_service-oneUsers)]

  service-two:
    image: miproduct:develop
    environment:
      - ENVIRONMENT=Staging
    networks:
      - proxy_public
    deploy:
      replicas: 1
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=staging.midomain.com
        - com.df.servicePath=/orchestrator/,/hub/
        - com.df.reqPathSearch=/orchestrator/
        - com.df.reqPathReplace=/
        - com.df.port=5000
        - com.df.users=user:P@ss...,user1:P@ss...
        - com.df.setReqHeader=X-Via %[env(HOSTNAME)],X-Username %[http_auth_group(stack_service-twoUsers)]

networks:
  proxy_public:
    external: true

```

**Describe the results you received:**
When I try to go to https://staging.midomain.com/orchestrator/ in the proxy log I see its trying to send the request to `service-one`. 

**Describe the results you expected:**
I expect when the user go to https://staging.midomain.com/hub go to `service-two` and the try to https://staging.midomain.com/orchestrator/ go to `service-two` but replace `/orchestrator/` with `/`

**Additional information you deem important (e.g. issue happens only occasionally):**
Happens occasionally, after several restarts.

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I tried on Amazon Linux (Docker 17.03.2-ce) and Ubuntu (Docker 17.07.0-ce), same results
