### ISSUE TITLE
Srawm-listener -> Proxy

### ISSUE THREAD

**Issue by aleskinen** [vfarcic/docker-flow-proxy#371]
If I have:
```
  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
```
Is it ok to have_
```
  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
```
Now I get error from swarm-listener not when it tries to update proxy and it is maybe because i changed ports to host mode. I need this to log real ip addresses of web users.

Thank you for any help.
