### ISSUE TITLE
How to redirect path without trailing slash to a path with trailing slash

### ISSUE THREAD

**Issue by remy-tiitre** [vfarcic/docker-flow-proxy#390]
Portainer is one of such applications. Its easy to get it working with docker flow proxy. All you need is:
      labels:
        - com.df.notify=true
        - com.df.connectionMode=http-keep-alive
        - com.df.servicePath=/portainer
        - com.df.reqPathSearch=/portainer/
        - com.df.reqPathReplace=/
        - com.df.port=9000
But then the url .../portainer does not work as all the assets are read from root folder and not sent to portainer service. .../portainer/ works fine tough. Is there a simple way to configure service so that path without trailing slash would be redirected to a path with trailing slash? Or I have to do it with some templateFePath hacking by writing my own HAProxy template?

**Comment by vfarcic** [comment]
It would help a lot if you could modify the HAProxy config and paste the changes that should be applied. Like that, I should be able to add a new option (or modify an existing one) to accomplish that. Would that be OK? If it would, you can:

1. Run DFP as a single replica
2. Enter into DFP replica container
3. `apk add -U curl`
4. `vi /cfg/haproxy.cfg`
5. Modify and save
6. `curl localhost:8080/v1/docker-flow-proxy/reload`
7. Test whether Portainer is accessible

**Comment by yarmorell** [comment]
I had faced with the same problem and added to DFP config env variable:
`- EXTRA_FRONTEND=acl is_root path -i /,acl missing_slash path_reg  ^/*/[^/]*$$,http-request redirect code 301 prefix / append-slash if missing_slash !is_root`

**Comment by vfarcic** [comment]
I'm not sure that it would make sense to add that as a new parameter to DFP. The solution proposed by @yarmorell looks good. Please let me know if you disagree and I'll reopen the issue.

**Comment by hcsas** [comment]
@vfarcic Is it expected behaviour that adding a templateFePath replaces any and all other parameters derived from com.df frontend labels set in the container? I would of thought that having the ability to set additional parameters tied to a service or group of services through a template file is more flexible/ manageable that using the EXTRA_FRONTEND hammer on the DFP itself -  parsing a snippet from a template file whilst still respecting regular com.df labels might achieve that?

**Comment by hcsas** [comment]
Not necessarily. I have a scenario where I need to check whether a custom header is present, then redirect depending on the result. This requires a couple of new acls and a redirect 301 statement which I can't figure out how to do with com.df labels in the container service yaml. I can achieve the desired result by using EXTRA_FRONTEND though that requires hard coding parameters which is not ideal. Alternatively, I can use a template snippet containing only the custom commands though I cannot then use additional labels in the yaml for the frontend as they are replaced.

Anyway, it's Christmas, stop working and have a lovely day!

**Comment by SimonHeimberg** [comment]
> EXTRA_FRONTEND=acl is_root path -i /,acl missing_slash path_reg  ^/*/[^/]*$$,http-request redirect code 301 prefix / append-slash if missing_slash !is_root

I seem to be misunderstanding some part, or it does not work the same anymore, or ...

should this stack file work? (redirect myhost://portainer to myhost://portainer/)
```yaml
services:
  portainer:
    image: portainer/portainer
    deploy:
      labels:
        - com.df.notify=true
        - com.df.connectionMode=http-keep-alive
        - com.df.servicePath=/portainer
        - com.df.reqPathSearch=/portainer/
        - com.df.reqPathReplace=/
        - com.df.port=9000
      placement:
        ...
    ...
  dfp:
    image: dockerflow/docker-flow-proxy
    environment:
      LISTENER_ADDRESS: swarm-listener
      MODE: swarm
      EXTRA_FRONTEND: "acl is_root path -i /,acl missing_slash path_reg ^/*/[^/]*$$,http-request redirect code 301 prefix / append-slash if missing_slash !is_root"
    ...
```
