### ISSUE TITLE
One Domain multiple services

### ISSUE THREAD

**Issue by Vad1mo** [vfarcic/docker-flow-proxy#409]
I have two services on the domain app.company.com, "Website" and "API".

The API Service should receiver traffic for this path only

`app.company.com/v2/*`

The Website should receive traffic on this paths:

```
app.company.com/*
app.company.com/v2/token
app.company.com/v2/webhook
```

I tried to create a setup with traefik some time ago but failed, as traefik can't support such use cases. However it was fairly easy to create a setup for nginx, but its all manual  and not automated in any way.  So I was wondering if such an setup would be possible with DFP.

I created a small compose file, that will print out if the right service was called.

```
  
  version: '3.5'
  services:

#---#
  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - SERVICE_NAME=proxy_proxy      
    deploy:
      mode: global
      # replicas: 1
      placement:
        constraints: [node.role == worker]

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy_proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy_proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]
#---#
    service_web:
      image: vad1mo/hello-world-service
      hostname: web
      deploy:      
        labels:
          - com.df.servicePath=/,/v2/token,/v2/webhooks/events
          - com.df.notify=true
          - com.df.distribute=true
          - com.df.port=5050
          - com.df.serviceDomain=docker.for.mac.localhost          
#---#
    service_api:
      image: vad1mo/hello-world-service
      hostname: api
      deploy:      
        labels:
          - com.df.servicePath=/2/
          - com.df.notify=true
          - com.df.distribute=true
          - com.df.port=5050
          - com.df.serviceDomain=docker.for.mac.localhost   

  networks:
    default:
      name: proxy    
```
