### ISSUE TITLE
df proxy failed to forward access to my specified container

### ISSUE THREAD

**Issue by alexya** [vfarcic/docker-flow-proxy#412]
**Description**
I used the DF proxy to forward access to 443 to my portainer website, but failed.

In fact, my goal is to use https://myserver.com/portainer to access my portainer server website.

**Steps to reproduce the issue:**

I can use http://myserver.com to access the simple web site. And I can access portainer by https://myserver.com:1444 very well. But when I used https://myserver.com/portainer, I failed.

docker-compose.yml:
```
version: "3"

services:

  # From http://proxy.dockerflow.com/swarm-mode-stack/
  server:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm_listener
      - MODE=swarm
    deploy:
      replicas: 1

  swarm_listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

  # a simple web site to verify the proxy can work well
  simple_site:
    image: yeasy/simple-web:latest
    networks:
      - proxy
    deploy:
      labels:
        - com.df.servicePath=/simple
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=80
      replicas: 1

networks:
  proxy:
    external: true
```

portainer.yml
```
version: '3'

volumes:
  data:

networks:
  proxy:
    external: true

services:
  server:
    image: portainer/portainer
    ports:
      - 1444:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/certs:/certs
      - data:/data
    command: -H unix:///var/run/docker.sock --ssl
    networks:
     - proxy
    deploy:
      labels:
        - com.df.servicePath=/portainer
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=443
      replicas: 1
      restart_policy:
        delay: 5s
        max_attempts: 5
        window: 5s
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.25'
          memory: 150M
```

**Describe the results you received:**
```
Error response
Error code 404.

Message: File not found.

Error code explanation: 404 = Nothing matches the given URI.
```

**Describe the results you expected:**
I hope https://myserver.com/portainer could show portainer website successfully. 
http://myserver.com/simple can't forward to simple web site either. 

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Comment by alexya** [comment]
try more, 
```
version: '3'

volumes:
  data:

networks:
  proxy:
    external: true

services:
  server:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data
    command: -H unix:///var/run/docker.sock
    networks:
     - proxy
    deploy:
      labels:
        - com.df.servicePath=/portainer
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=9000
        - com.df.srcPort=80
```

And I checked the haproxy.cfg from df-proxy container. 
```
frontend services
    bind *:80
    bind *:443
    mode http

    acl url_portainer_server9000_0 path_beg /portainer
    acl srcPort_portainer_server80 dst_port 80
    use_backend portainer_server-be9000_0 if url_portainer_server9000_0 srcPort_portainer_server80
    acl url_proxy_sample_site80_0 path_beg /
    use_backend proxy_sample_site-be80_0 if url_proxy_sample_site80_0

backend portainer_server-be9000_0
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server portainer_server portainer_server:9000


backend proxy_sample_site-be80_0
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    server proxy_sample_site proxy_sample_site:80
```
