### ISSUE TITLE
Cannot setup affinity configuration 

### ISSUE THREAD

**Issue by HDimka** [vfarcic/docker-flow-proxy#414]
Hello, I am trying to setup affinity that described in this article - https://www.haproxy.com/blog/load-balancing-affinity-persistence-sticky-sessions-what-you-need-to-know/
 but I cannot do this using my compose file:

```
version: '3.0'
services:
  http:
    image: emilevauge/whoami
    networks:
      - proxy
    deploy:
      replicas: 2
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/http/
        - com.df.reqPathSearch=/http/
        - com.df.reqPathReplace=/renamed/
        - com.df.port=80
    

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 8000:8000
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - BACKEND_EXTRA=balance roundrobin cookie SERVERID insert indirect nocache, server s1 10.0.0.4:8080 check cookie s1
    deploy:
      replicas: 1

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]


networks:
  proxy:
    external: true
```

Variable BACKAND_EXTRA gives nothing, backend remains the same:
```
frontend services
    bind *:80
    bind *:443
    mode http

    acl url_prod_http80_0 path_beg /http/
    use_backend prod_http-be80_0 if url_prod_http80_0

backend prod_http-be80_0
    mode http
    http-request add-header X-Forwarded-Proto https if { ssl_fc }
    http-request set-path %[path,regsub(/http/,/renamed/)]
    server prod_http prod_http
```
Please tell me where I am wrong and how I can setup affinity or IP sticknes.
