### ISSUE TITLE
How to track down ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by Vad1mo** [vfarcic/docker-flow-proxy#416]
I have an issue where every 1 of 10 request receives an ERR_SSL_PROTOCOL_ERROR. Now I want to track down this issue however there aren't anything in the DFP logs.

How can we track down this sporadic error?

We have a bit of a special setup with an TCP LB in front of DFP (3 Nodes) the TCP LB is configured in Round Robin with Source IP sticky session. So each request should go to the same DFP node.

**Comment by vanbroup** [comment]
We look to have a similar issue but without any TCP LB in front, in this setup, we have a three-node swarm cluster.  With a simple curl loop that makes a request to one specific node in the cluster, you can clearly see the problem.

(ip address and hostname redacted)
```
while :; do
        i=$((i + 1))
        echo $i `curl -sS --tlsv1.2 --resolve redacted.example.com:443:1.2.3.4 https://redacted.example.com`
        sleep 2
done
```

Result:
```
1 404 page not found
2 404 page not found
curl: (51) SSL: no alternative certificate subject name matches target host name 'redacted.example.com'
3
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
4
5 404 page not found
6 404 page not found
7 404 page not found
curl: (51) SSL: no alternative certificate subject name matches target host name 'redacted.example.com'
8
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
9
10 404 page not found
11 404 page not found
12 404 page not found
curl: (51) SSL: no alternative certificate subject name matches target host name 'redacted.example.com'
13
14 404 page not found
15 404 page not found
16 404 page not found
curl: (51) SSL: no alternative certificate subject name matches target host name 'redacted.example.com'
17
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
18
19 404 page not found
20 404 page not found
```

**Comment by Vad1mo** [comment]
Interesting, exactly the same error.  We have 3 worker nodes each running a DFP instance. We  @nib0r `docker-flow-proxy-letsencrypt` to get our certs that we store in cinder fs and swarm secrets.  Our Cluster is running on OpenStack.

Error:
```
curl https://ci.8gears.com
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
> curl https://ci.8gears.com
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
> curl https://ci.8gears.com
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
> curl https://ci.8gears.com
  <!DOCTYPE html><html><head resURL="/static/ff25c403" data-rooturl="" data-resurl="/static/ff25c403">
```

I will bypass the LB and try to  reproduce the error, I think this should be reproducible. 

CI Jenkins config for DFP.

```
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=8080
        - com.df.serviceDomain=ci.8gears.com
        - com.df.letsencrypt.host=ci.8gears.com
        #- com.df.redirectWhenHttpProto=true
        - com.df.httpsOnly=true
        - com.df.httpsRedirectCode=301
        #- com.df.srcPort=443
        - com.df.letsencrypt.email=le@8gears.com
```

Here is our proxy config, nothing fancy
```
version: "3.4"
services:
  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - net
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - SERVICE_NAME=proxy_proxy
      # - DEFAULT_PORTS=80 accept-proxy,443 accept-proxy:ssl
    deploy:
      mode: global
      # replicas: 1
      placement:
        constraints: [node.role == worker]

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy-le:8080/v1/docker-flow-proxy-letsencrypt/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy_proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

  proxy-le:
    image: nib0r/docker-flow-proxy-letsencrypt
    networks:
      - net
    environment:
      - DF_PROXY_SERVICE_NAME=proxy_proxy
      # - LOG=debug
      # - CERTBOT_OPTIONS=--staging
    volumes:
      # link docker socket to activate secrets support.
      - /var/run/docker.sock:/var/run/docker.sock
      # create a dedicated volume for letsencrypt folder.
      # MANDATORY to keep persistent certificates on DFPLE.
      # Without this volume, certificates will be regenerated every time DFPLE is recreated.
      # OPTIONALY you will be able to link this volume to another service that also needs certificates (gitlab/gitlab-ce for example)
      - le-certs:/etc/letsencrypt
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]      
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.servicePath=/.well-known/acme-challenge
        - com.df.port=8080
networks:
  net:
volumes:
   le-certs:
    driver: cinder
    driver_opts:
      size: 1

```

**Comment by Vad1mo** [comment]
Searching on the internet I found some references:


> It appears there is no SSL/TLS server listening on 10.0.10.90:50060. There is a server listening, its just not SSL/TLS. [ref](https://stackoverflow.com/questions/21135637/error140770fcssl-routinesssl23-get-server-hellounknown-protocol)



Reproducible be trying to establish a TLS connection to an HTTP endpoint. e.g.
```
curl https://ci.8gears.com:80
curl: (35) error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol
```

**Comment by vanbroup** [comment]
We are using docker secrets to store the pem files and regular publicly trusted EV certificates. I have redeployed the proxy stack and found that the problem became much less frequent.

I also upgraded the docker compose file to version 3.1 and added the secret ids to the `secrets` section so that the proxy can always access the certificates.

Also, and probably more closely related to the problem I found one service that was not connected to the proxy overlay network, this looked to have caused some issues with `could not resolve address` resulting in the proxy to fail to start with `Failed to initialize server(s) addr.`. The strange thing is that this misconfigured service was working fine? But maybe with instances frequently restarting this could have caused the random errors.

I'm not sure how often the ha-proxy is restarted for updates but I feel strongly that this is related to the problem and it might be interesting to see if **seamless reloads** can be configured for docker flow proxy?

https://www.haproxy.com/blog/truly-seamless-reloads-with-haproxy-no-more-hacks/

**Comment by Vad1mo** [comment]
@vanbroup, It almost looks we are working on the swarm cluster. 

I also see `ould not resolve address` and `Failed to initialize server(s) addr.`  this seems to cause problems to DFP. We are using OpenFass that has a few dozens of containers. After removing the stack it got a bit better.

Can you post an example regarding your **secrets** section and ids. I couldn't find anything on the net.

**Comment by Vad1mo** [comment]
@vfarcic are  **seamless reloads** on the roadmap of DFP or are they already included?

**Comment by vanbroup** [comment]
Hi @Vad1mo, here is a redacted version of my config:

```
version: "3.1"

services:

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
      - STATS_USER=adminuser
      - STATS_PASS=adminpassword
      - STATS_URI=/proxy/stats
      - SKIP_ADDRESS_VALIDATION=false
      - RECONFIGURE_ATTEMPTS=5
      - HTTPS_ONLY=true
    secrets:
      - cert_www.example.com
      - cert_www.example2.com
    deploy:
      mode: global

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external: true

secrets:
  cert_www.example.com:
    external: true
  cert_www.example2.com:
    external: true

```
