### ISSUE TITLE
Grafana not working properly using serviceDomain label

### ISSUE THREAD

**Issue by stuart89** [vfarcic/docker-flow-proxy#418]
Hi, 
I'm setting up grafana in aws with Docker for aws cluster. I configured dfp with serviceDomain label.
This is my compose file:

```
version: '3'

services:

  grafana:
    image: grafana/grafana:${GRAFANA_TAG:-4.6.0}
    networks:
      - monitor
      - proxy
    deploy:
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.serviceDomain=grafs.mydomain.com
        - com.df.port=3000

networks:
  monitor:
    external: true
  proxy:
    external: true

```
I can access the login page (http://grafs.mydomain.com/login), 
but once I'm logged I get a black screen. 
When I inspect the network call to their api http://grafs.mydomain.com/api/dashboards/home returns **404**
The only way I was able to make it work is by exposing the port 3000 and accessing http://grafs.mydomain.com:3000
