### ISSUE TITLE
Portainer Setup with DFP

### ISSUE THREAD

**Issue by shabbirkagalwala** [vfarcic/docker-flow-proxy#424]
**Description**

Hi Viktor,

First of all thank you for this awesome project! 

I would like your help with some setup or configuration I might be doing wrong. So I am trying to use Portainer with DFP (see command below) and even though I define ports that it can be accessible on, I can still get to it without the port in the url. For example
`https://portainer.companydomain.com` works as well as `https://portainer.companydomain.com:7442`

Is there a way I can make it to not respond to `https://portainer.companydomain.com`. I only want 
`https://portainer.companydomain.com:7442` to be accessible since we have that port locked down to our corporate IP.

```
docker service create \
    --name portainer --publish 7442:9000 \
    --mount type=bind,src=/var/run/docker.sock,dst=/var/run/docker.sock \
    --mount type=bind,src=/home/centos/portainer,dst=/data \
    --network app --network proxy --label com.df.notify=true \
    --label com.df.distribute=true --label com.df.serviceDomain=portainer.companydomain.com \
    --label com.df.servicePath=/ --label com.df.port=9000 --label com.df.xForwardedProto=true --label com.df.redirectWhenHttpProto=true \
    --constraint 'node.hostname==ip-192-168-24-172.eu-west-1.compute.internal' \
    portainer/portainer \
    -H unix:///var/run/docker.sock
```

I read your comment on another issue to use subdomain instead of paths and that is why I am using serviceDomain as an label.

**Steps to reproduce the issue:**
1. Start portainer with the docker command above

**Describe the results you received:**
This makes both `https://portainer.companydomain.com`  and `https://portainer.companydomain.com:7442` accessible

**Describe the results you expected:**
I want it to be restricted or accessible only at `https://portainer.companydomain.com:7442`

**Additional information you deem important (e.g. issue happens only occasionally):**

**Additional environment details (AWS, VirtualBox, physical, etc.):**
AWS - EC2 - `centos-release-7-4.1708.el7.centos.x86_64`

Docker Version
```
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:10:14 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:46 2017
  OS/Arch:	linux/amd64
  Experimental:	false
```

Let me know if I can provide any additional information.

Thank you!

**Comment by vfarcic** [comment]
Are you trying to make only that application accessible on the port 7442 or each service should have a different port?

**Comment by shabbirkagalwala** [comment]
Hi Viktor, thank you for the reply. I am trying to make only portainer accessible on only 7442 i.e. `https://portainer.companydomain.com:7442` and not on 443. Currently it is accessible on both the ports.

**Comment by remy-tiitre** [comment]
For Portainer you have to use:

**Comment by Vad1mo** [comment]
FYI here is my portainer config:


```yml
# Rolls out Portainer 
# -- Make sure Docker Flow Porxy exists and the network "proxy" also exists 
# -- (Optional) Store Data on CINDER Remote Storage, make sure the plugin is installed.
version: '3'

services:
  portainer:
    image: portainer/portainer:1.16.1
    networks:
      - net
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role == manager           
      labels:
        - com.df.notify=true
        - com.df.distribute=true
        - com.df.port=9000
        - com.df.serviceDomain=cloud.example.com
        - com.df.httpsOnly=true
        - com.df.httpsRedirectCode=301
        - com.df.letsencrypt.host=cloud.example.com
        - com.df.letsencrypt.email=hostmaster@example.com
networks:
  net:
  proxy:
    external: true
volumes:
  portainer-data:
```
