### ISSUE TITLE
Bug: Firefox reports: "SSL_ERROR_RX_RECORD_TOO_LONG"

### ISSUE THREAD

**Issue by Nols1000** [vfarcic/docker-flow-proxy#445]
**Description**
The DFP doesn't encrypt the 503 if no service is configured. Also the error html looks different than normal.

**Steps to reproduce the issue:**
1. Start DFP with this docker-compose.yml
````
version: '3.5'
services:
  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - "MODE=swarm"
      - "HTTPS_ONLY=true"
      - "LISTENER_ADDRESS=swarm-listener"
    secrets:
      - cert_somedomain.pem
      - cert_someotherdomain.pem
    deploy:
      replicas: 1

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure"
      - "DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove"
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external: true
  default:
    external: false

secrets:
  cert_somedomain.pem:
    file: /etc/ssl/somedomain.pem
  cert_someotherdomain.pem:
    file: /etc/ssl/someotherdomain.pem
````
2. Go to https://somedomain/

**Describe the results you received:**
Chrome reports: "ERR_SSL_PROTOCOL_ERROR"
Firefox reports: "SSL_ERROR_RX_RECORD_TOO_LONG"

**Describe the results you expected:**
Get a 404 or 503 properly send throug https.

**Additional information you deem important (e.g. issue happens only occasionally):**
The issue seem to happen only if there is no service behind the proxy.

**Comment by vfarcic** [comment]
It seems that the certificate is not correct.

**Comment by Nols1000** [comment]
I know that the certificate is right. It works after I start a service that uses DFP. I think the DFP isn't configured right after the start.

**Comment by felicienfrancois** [comment]
We have a similar issue with a docker-flow-proxy + nib0r/docker-flow-proxy-letsencrypt (using docker certs).
After restarting docker-flow-proxy, I get the same "SSL_ERROR_RX_RECORD_TOO_LONG" error. I need to delete secrets and makes docker-flow-proxy-letsencrypt regenerate the certificates (and also reconfigure the proxy) to makes it work again.
It seems not to reconfigure itself automatically after restart.

Not sure if its the same issue and if it's a bug or a misconfiguration.

```
version: "3.4"

services:

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    depends_on:
      - swarm-listener
    environment:
      LISTENER_ADDRESS: swarm-listener
      MODE: swarm
      SERVICE_NAME: proxy_proxy
      CHECK_RESOLVERS: 1

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DF_NOTIFY_CREATE_SERVICE_URL: http://letsencrypt:8080/v1/docker-flow-proxy-letsencrypt/reconfigure
      DF_NOTIFY_REMOVE_SERVICE_URL: http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

  letsencrypt:
    image: nib0r/docker-flow-proxy-letsencrypt
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - letsencrypt:/etc/letsencrypt
    environment:
      DF_PROXY_SERVICE_NAME: proxy_proxy
    deploy:
      labels:
        - com.df.notify=true
        - com.df.servicePath=/.well-known/acme-challenge
        - com.df.port=8080

volumes:
  letsencrypt:

networks:
  proxy:
    external: true
```
