### ISSUE TITLE
HAProxy not starting

### ISSUE THREAD

**Issue by unclebob418** [vfarcic/docker-flow-proxy#447]
**Description**
vfarcic/docker-flow-proxy:latest not starting

**Steps to reproduce the issue:**
1. `docker swarm init` (only using a single note atm)
1. `docker network create --driver overlay proxy`
1. `docker stack deploy -c dfproxy.yml proxy` (where dfproxy.yml is the same as https://github.com/vfarcic/docker-flow-proxy/blob/master/docker-compose-stack.yml but only using 1 replica as I only have one node)

```
version: "3"

services:

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - 80:80
      - 443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      replicas: 1

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external: true

```

**Describe the results you received:**
vfarcic/docker-flow-proxy:latest dies after approx 15 seconds. repeated restarts.
```
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                            PORTS                       NAMES
fb28cdccc74c        vfarcic/docker-flow-proxy:latest            "/sbin/tini -g -- do…"   11 seconds ago      Up 4 seconds (health: starting)   80/tcp, 443/tcp, 8080/tcp   proxy_proxy.1.j0xax9cfseahgmbz8b78186qs
1f0c6d440c0e        vfarcic/docker-flow-swarm-listener:latest   "docker-flow-swarm-l…"   6 minutes ago       Up 5 minutes (healthy)            8080/tcp                    proxy_swarm-listener.1.un37vvwowk8mxuswbd6sft4gu
ubuntu@ip-10-0-0-125:~$ docker ps
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                            PORTS                       NAMES
fb28cdccc74c        vfarcic/docker-flow-proxy:latest            "/sbin/tini -g -- do…"   16 seconds ago      Up 9 seconds (health: starting)   80/tcp, 443/tcp, 8080/tcp   proxy_proxy.1.j0xax9cfseahgmbz8b78186qs
1f0c6d440c0e        vfarcic/docker-flow-swarm-listener:latest   "docker-flow-swarm-l…"   6 minutes ago       Up 6 minutes (healthy)            8080/tcp                    proxy_swarm-listener.1.un37vvwowk8mxuswbd6sft4gu
ubuntu@ip-10-0-0-125:~$ docker ps
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                             PORTS                       NAMES
fb28cdccc74c        vfarcic/docker-flow-proxy:latest            "/sbin/tini -g -- do…"   21 seconds ago      Up 14 seconds (health: starting)   80/tcp, 443/tcp, 8080/tcp   proxy_proxy.1.j0xax9cfseahgmbz8b78186qs
1f0c6d440c0e        vfarcic/docker-flow-swarm-listener:latest   "docker-flow-swarm-l…"   6 minutes ago       Up 6 minutes (healthy)             8080/tcp                    proxy_swarm-listener.1.un37vvwowk8mxuswbd6sft4gu
ubuntu@ip-10-0-0-125:~$ docker ps
CONTAINER ID        IMAGE                                       COMMAND                  CREATED             STATUS                      PORTS                       NAMES
fb28cdccc74c        vfarcic/docker-flow-proxy:latest            "/sbin/tini -g -- do…"   24 seconds ago      Up 17 seconds (unhealthy)   80/tcp, 443/tcp, 8080/tcp   proxy_proxy.1.j0xax9cfseahgmbz8b78186qs
1f0c6d440c0e        vfarcic/docker-flow-swarm-listener:latest   "docker-flow-swarm-l…"   6 minutes ago       Up 6 minutes (healthy)      8080/tcp                    proxy_swarm-listener.1.un37vvwowk8mxuswbd6sft4gu

```
service shows 0 replicas for proxy_proxy:
```
ubuntu@ip-10-0-0-125:~$ docker service ls
ID                  NAME                   MODE                REPLICAS            IMAGE                                       PORTS
5rx22hus0gyr        proxy_proxy            replicated          0/1                 vfarcic/docker-flow-proxy:latest            *:80->80/tcp, *:443->443/tcp
n0o5z1acpxw6        proxy_swarm-listener   replicated          1/1                 vfarcic/docker-flow-swarm-listener:latest

```
service logs don't have anything particularly useful
```
ubuntu@ip-10-0-0-125:~$ docker service logs proxy_proxy
proxy_proxy.1.tyfqo5rw7tuy@ip-10-0-0-125    | 2018/03/20 11:08:05 Starting HAProxy
proxy_proxy.1.mcnynftz808r@ip-10-0-0-125    | 2018/03/20 11:09:46 Starting HAProxy
ubuntu@ip-10-0-0-125:~$ docker service logs proxy_proxy
proxy_proxy.1.i0pifcakpnvv@ip-10-0-0-125    | 2018/03/20 11:10:11 Starting HAProxy
proxy_proxy.1.tyfqo5rw7tuy@ip-10-0-0-125    | 2018/03/20 11:08:05 Starting HAProxy
ubuntu@ip-10-0-0-125:~$ docker service logs proxy_proxy
proxy_proxy.1.tyfqo5rw7tuy@ip-10-0-0-125    | 2018/03/20 11:08:05 Starting HAProxy
proxy_proxy.1.i0pifcakpnvv@ip-10-0-0-125    | 2018/03/20 11:10:11 Starting HAProxy
ubuntu@ip-10-0-0-125:~$ docker service logs proxy_proxy
proxy_proxy.1.tyfqo5rw7tuy@ip-10-0-0-125    | 2018/03/20 11:08:05 Starting HAProxy
proxy_proxy.1.lzk35lbem1x0@ip-10-0-0-125    | 2018/03/20 11:10:36 Starting HAProxy

```
**Describe the results you expected:**
2 containers running in the service

**Additional information you deem important (e.g. issue happens only occasionally):**
tried a couple of arbitrary versions going back several months. **works using vfarcic/docker-flow-proxy:17.10.12-41** (maybe later versions also, just glad I've got a working proxy now :))

**Additional environment details (AWS, VirtualBox, physical, etc.):**
1. using Ubuntu on AWS 16.04.4 LTS (GNU/Linux 4.4.0-1052-aws x86_64)
1. brand new install of docker using convenience script as of yesterday
1. using docker swarm
