### ISSUE TITLE
Support for arm (rpi)

### ISSUE THREAD

**Issue by RaymondMouthaan** [vfarcic/docker-flow-proxy#449]
Hello @vfarcic 

Currently i am using a 5 rpi docker swarm cluster with HAProxy  with several backends. Now i came across your project and very well documented site. I am really interested to use this project for my swarm. Unfortunately I couldn't find the arm docker images for it.

Are there any plans to build the arm images as well? If needed it like to work together to make it available too for arm. 

After searching i found several projects to support arm, but they are quite out-dated or undocumented.

- docker-hub: taylorsmcclure/docker-flow-arm (more than a year old) -> https://github.com/mastermindg/docker-flow-proxy

- docker-hub: monsonnl/docker-flow-proxy (about 8 months old) -> https://github.com/monsonnl/docker-flow-proxy

- docker-hub: dsbaha/docker-flow-proxy (about 3 months old), but no GitHub available. 

Deploying the example docker-compose-stack.yml file with some modifications to use the dsbaha/docker-flow-proxy and dsbaha/docker-flow-swarm-listener images, seems to run fine.

```
version: "3"

services:

  proxy:
    image: dsbaha/docker-flow-proxy
    ports:
      - 9011:80
      - 9443:443
    networks:
      - proxy
    environment:
      - LISTENER_ADDRESS=swarm-listener
      - MODE=swarm
    deploy:
      replicas: 2

  swarm-listener:
    image: dsbaha/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints: [node.role == manager]

networks:
  proxy:
    external: true
```

![screen shot 2018-03-25 at 13 24 24](https://user-images.githubusercontent.com/25717738/37874459-e00eeadc-302f-11e8-82d6-429aba17d3ea.png)

Best regards,
Raymond
