### ISSUE TITLE
What's up with the color parameter?

### ISSUE THREAD

**Issue by cternes** [vfarcic/docker-flow-proxy#46]
If I use the serviceColor parameter while updating the proxy configuration, it seems to break the proxy configuration. 

If I update the proxy like this (with color):
`curl "localhost:8080/v1/docker-flow-proxy/reconfigure?serviceName=abc&servicePath=/v1&serviceColor=blue"`

it seems that the _haproxy.cfg_ is missing the server component in the backend configuration section. 

However if I update the proxy like this (without color):
`curl "localhost:8080/v1/docker-flow-proxy/reconfigure?serviceName=pesc&servicePath=/v1"`

it works fine.

Any idea what could be the problem?

**Comment by vfarcic** [comment]
Sorry for not responding earlier. I was away for almost a week now.

Can you send me the command you used to run the proxy container?

Feel free to ping me on Skype (user: vfarcic) or HangOuts (user: viktor@farcic.com) if direct communication suits you better.

**Comment by cternes** [comment]
I'm running the proxy with docker-compose. Here is my _docker-compose.yml_:

```
version: '2'

services:
  consul-server:
    container_name: consul
    image: consul:v0.7.0
    network_mode: host
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true}'
    command: agent -server -bind=$DOCKER_IP -bootstrap-expect=1 -client=0.0.0.0 -ui

  registrator:
    container_name: registrator
    image: registrator:v7
    network_mode: host
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
    depends_on:
      - consul-server
    command: -ip $DOCKER_IP consul://$CONSUL_IP:8500

  proxy:
    container_name: docker-flow-proxy
    image: vfarcic/docker-flow-proxy:1.90
    environment:
      CONSUL_ADDRESS: $CONSUL_IP:8500
      PROXY_INSTANCE_NAME: docker-flow
    volumes:
      - ./test_configs/:/consul_templates/
    depends_on:
      - consul-server
    ports:
      - 80:80
      - 443:443
      - 8000:8080
```
