### ISSUE TITLE
Override `serviceName` with Docker Swarm Mode

### ISSUE THREAD

**Issue by vovimayhem** [vfarcic/docker-flow-proxy#84]
Hi! I've just gave `docker-flow-proxy` a try. Found the following opportunity:

I'm deploying a stack of services named "blue" to a Swarm using Docker v1.13 `docker stack deploy` command:

```
docker stack deploy --compose-file=docker-compose.yml blue
```

The Compose file contents:
```
version: '3'
networks:
  proxy:
    external: true
services:
  web:
    image: vovimayhem/test-website:blue
    networks:
      - default         # This stack's network
      - proxy           # The App Routing Network (Docker Flow: Proxy)
    deploy:
      labels:
        com.df.notify: "true"
        com.df.distribute: "true"
        com.df.servicePath: /
        com.df.serviceName: blue
        com.df.serviceDomain: example.com
        com.df.port: 80
      placement:
        constraints:
          - node.labels.app-host == true
```

As you may know, `docker stack deploy` will prepend the stack name to each of the services in the stack, which will result in a service called `blue_web` in this case. What I'm trying to do is to override the "subdomain" name that will route requests to the service I created - in this case, to route `http://blue.example.com` to the `blue_web` service.

However this does not work. I did notice in the README's [Reconfigure](https://github.com/vfarcic/docker-flow-proxy#reconfigure) section that `serviceName` is expected to "match the name of the Swarm service". Further more, I tried setting a service alias for the `proxy` network:

```
# (...)
services:
  web:
    # (...)
    networks:
      default:
      proxy:
        aliases:
          - blue
    # (...)
```
...but this didn't work either.

Is there currently a way to achieve this??? Or is it a feature that is currently not present, and would be implemented eventually?
